/* tslint:disable */
/* eslint-disable */
/**
 * 数据库设计项目 API
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface ApiResponse {
    /**
     * 业务状态码，只使用 200、400、401、403、404、409、500。
     */
    'code': ApiResponseCodeEnum;
    /**
     * 返回结果说明。
     */
    'message': string;
    /**
     * 实际业务数据，无数据时返回 null。
     */
    'data': any | null;
}

export const ApiResponseCodeEnum = {
    NUMBER_200: 200,
    NUMBER_400: 400,
    NUMBER_401: 401,
    NUMBER_403: 403,
    NUMBER_404: 404,
    NUMBER_409: 409,
    NUMBER_500: 500,
} as const;

export type ApiResponseCodeEnum = typeof ApiResponseCodeEnum[keyof typeof ApiResponseCodeEnum];

export interface ErrorResponse {
    /**
     * 错误业务状态码，只使用 400、401、403、404、409、500。
     */
    'code': ErrorResponseCodeEnum;
    /**
     * 错误原因说明。
     */
    'message': string;
    /**
     * 错误响应无业务数据，固定返回 null。
     */
    'data': any | null;
}

export const ErrorResponseCodeEnum = {
    NUMBER_400: 400,
    NUMBER_401: 401,
    NUMBER_403: 403,
    NUMBER_404: 404,
    NUMBER_409: 409,
    NUMBER_500: 500,
} as const;

export type ErrorResponseCodeEnum = typeof ErrorResponseCodeEnum[keyof typeof ErrorResponseCodeEnum];

export interface LoginData {
    /**
     * JWT 访问令牌。
     */
    'accessToken': string;
    /**
     * token 过期时间或有效期，具体含义以后端实现为准。
     */
    'expires': number;
}
export interface LoginRequest {
    'userNo': string;
    'password': string;
}
export interface LoginResponse {
    /**
     * 业务状态码，只使用 200、400、401、403、404、409、500。
     */
    'code': LoginResponseCodeEnum;
    /**
     * 返回结果说明。
     */
    'message': string;
    'data': LoginData | null;
}

export const LoginResponseCodeEnum = {
    NUMBER_200: 200,
    NUMBER_400: 400,
    NUMBER_401: 401,
    NUMBER_403: 403,
    NUMBER_404: 404,
    NUMBER_409: 409,
    NUMBER_500: 500,
} as const;

export type LoginResponseCodeEnum = typeof LoginResponseCodeEnum[keyof typeof LoginResponseCodeEnum];

export interface PageQuery {
    /**
     * 当前页码，从 1 开始。
     */
    'page'?: number;
    /**
     * 每页数据数量。
     */
    'page_size'?: number;
}
export interface PageResult {
    /**
     * 数据总数。
     */
    'total': number;
    /**
     * 当前页码。
     */
    'page': number;
    /**
     * 每页数据数量。
     */
    'page_size': number;
    /**
     * 当前页数据。
     */
    'records': Array<any>;
}
export interface RegisterRequest {
    'userNo': string;
    'password': string;
    'userName': string;
    'phone': string;
    'email'?: string;
}
export interface RegisterResponse {
    /**
     * 业务状态码，只使用 200、400、401、403、404、409、500。
     */
    'code': RegisterResponseCodeEnum;
    /**
     * 返回结果说明。
     */
    'message': string;
    'data': any | null;
}

export const RegisterResponseCodeEnum = {
    NUMBER_200: 200,
    NUMBER_400: 400,
    NUMBER_401: 401,
    NUMBER_403: 403,
    NUMBER_404: 404,
    NUMBER_409: 409,
    NUMBER_500: 500,
} as const;

export type RegisterResponseCodeEnum = typeof RegisterResponseCodeEnum[keyof typeof RegisterResponseCodeEnum];

export interface UserData {
    'id'?: number;
    'name'?: string;
    'createdAt'?: string;
}
export interface UserTestResponse {
    /**
     * 业务状态码，只使用 200、400、401、403、404、409、500。
     */
    'code': UserTestResponseCodeEnum;
    /**
     * 返回结果说明。
     */
    'message': string;
    'data': Array<UserData> | null;
}

export const UserTestResponseCodeEnum = {
    NUMBER_200: 200,
    NUMBER_400: 400,
    NUMBER_401: 401,
    NUMBER_403: 403,
    NUMBER_404: 404,
    NUMBER_409: 409,
    NUMBER_500: 500,
} as const;

export type UserTestResponseCodeEnum = typeof UserTestResponseCodeEnum[keyof typeof UserTestResponseCodeEnum];


/**
 * SystemApi - axios parameter creator
 */
export const SystemApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 需要登录后访问，调用时请求头使用 Authorization: Bearer <token>。
         * @summary 获取测试用户数据表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserTest: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/getUserTest`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 登录接口不需要携带 Authorization 请求头。
         * @summary 登录
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login: async (loginRequest: LoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginRequest' is not null or undefined
            assertParamExists('login', 'loginRequest', loginRequest)
            const localVarPath = `/api/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 注册接口不需要携带 Authorization 请求头。
         * @summary 注册系统用户
         * @param {RegisterRequest} registerRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        register: async (registerRequest: RegisterRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'registerRequest' is not null or undefined
            assertParamExists('register', 'registerRequest', registerRequest)
            const localVarPath = `/api/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registerRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SystemApi - functional programming interface
 */
export const SystemApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SystemApiAxiosParamCreator(configuration)
    return {
        /**
         * 需要登录后访问，调用时请求头使用 Authorization: Bearer <token>。
         * @summary 获取测试用户数据表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserTest(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserTestResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserTest(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SystemApi.getUserTest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 登录接口不需要携带 Authorization 请求头。
         * @summary 登录
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LoginResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.login(loginRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SystemApi.login']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 注册接口不需要携带 Authorization 请求头。
         * @summary 注册系统用户
         * @param {RegisterRequest} registerRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async register(registerRequest: RegisterRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RegisterResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.register(registerRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SystemApi.register']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SystemApi - factory interface
 */
export const SystemApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SystemApiFp(configuration)
    return {
        /**
         * 需要登录后访问，调用时请求头使用 Authorization: Bearer <token>。
         * @summary 获取测试用户数据表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserTest(options?: RawAxiosRequestConfig): AxiosPromise<UserTestResponse> {
            return localVarFp.getUserTest(options).then((request) => request(axios, basePath));
        },
        /**
         * 登录接口不需要携带 Authorization 请求头。
         * @summary 登录
         * @param {SystemApiLoginRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(requestParameters: SystemApiLoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<LoginResponse> {
            return localVarFp.login(requestParameters.loginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 注册接口不需要携带 Authorization 请求头。
         * @summary 注册系统用户
         * @param {SystemApiRegisterRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        register(requestParameters: SystemApiRegisterRequest, options?: RawAxiosRequestConfig): AxiosPromise<RegisterResponse> {
            return localVarFp.register(requestParameters.registerRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for login operation in SystemApi.
 */
export interface SystemApiLoginRequest {
    readonly loginRequest: LoginRequest
}

/**
 * Request parameters for register operation in SystemApi.
 */
export interface SystemApiRegisterRequest {
    readonly registerRequest: RegisterRequest
}

/**
 * SystemApi - object-oriented interface
 */
export class SystemApi extends BaseAPI {
    /**
     * 需要登录后访问，调用时请求头使用 Authorization: Bearer <token>。
     * @summary 获取测试用户数据表
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getUserTest(options?: RawAxiosRequestConfig) {
        return SystemApiFp(this.configuration).getUserTest(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 登录接口不需要携带 Authorization 请求头。
     * @summary 登录
     * @param {SystemApiLoginRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public login(requestParameters: SystemApiLoginRequest, options?: RawAxiosRequestConfig) {
        return SystemApiFp(this.configuration).login(requestParameters.loginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 注册接口不需要携带 Authorization 请求头。
     * @summary 注册系统用户
     * @param {SystemApiRegisterRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public register(requestParameters: SystemApiRegisterRequest, options?: RawAxiosRequestConfig) {
        return SystemApiFp(this.configuration).register(requestParameters.registerRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



