-- ============================================================================
-- 工业制造物料进销存管理系统 · 建表脚本（Oracle 23ai Free / FREEPDB1）
-- 业务领域：电动平衡重叉车制造（CPD15 / CPD20 / CPD30）
-- 执行用户：DB_Design
-- 与设计文档差异（已修正项，详见 README）：
--   1. supplier_price 表字段修正：operator_id→price，补充 valid_from/valid_to
--   2. 文档中 text 类型统一改为 CLOB，并加 IS JSON 约束
--   3. VARCHAR2 按文档保留字节语义（AL32UTF8），种子数据已校验无汉字截断风险
--   4. material.current_version_id 与 bom_version 的循环外键用 ALTER 后置添加
--   5. 主键使用 GENERATED BY DEFAULT ON NULL AS IDENTITY，兼容显式插入与自增
-- ============================================================================

-- ---------- 1. 系统管理模块（被其他模块外键引用，最先建） ----------

CREATE TABLE sys_user (
    user_id          NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    employee_no      VARCHAR2(20)  NOT NULL UNIQUE,
    password_hash    VARCHAR2(128) NOT NULL,
    user_name        VARCHAR2(50)  NOT NULL,
    phone            VARCHAR2(20),
    email            VARCHAR2(100),
    status           VARCHAR2(10)  DEFAULT '有效' NOT NULL
                     CHECK (status IN ('有效','停用')),
    created_time     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    last_login_time  TIMESTAMP,
    pwd_update_time  TIMESTAMP
);

CREATE TABLE sys_role (
    role_id      NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    role_name    VARCHAR2(50)  NOT NULL,
    description  VARCHAR2(200),
    status       VARCHAR2(10)  DEFAULT '有效' NOT NULL
                 CHECK (status IN ('有效','停用'))
);

CREATE TABLE sys_permission (
    permission_id  NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    "resource"     VARCHAR2(100) NOT NULL,
    action         VARCHAR2(50)  NOT NULL,
    CONSTRAINT uk_perm UNIQUE ("resource", action)
);

CREATE TABLE sys_user_role (
    user_id  NUMBER(10) NOT NULL REFERENCES sys_user(user_id),
    role_id  NUMBER(10) NOT NULL REFERENCES sys_role(role_id),
    CONSTRAINT pk_sys_user_role PRIMARY KEY (user_id, role_id)
);

CREATE TABLE sys_role_permission (
    role_id        NUMBER(10) NOT NULL REFERENCES sys_role(role_id),
    permission_id  NUMBER(10) NOT NULL REFERENCES sys_permission(permission_id),
    CONSTRAINT pk_sys_role_perm PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE login_log (
    log_id       NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id      NUMBER(10) REFERENCES sys_user(user_id),
    login_time   TIMESTAMP  NOT NULL,
    ip_address   VARCHAR2(45) NOT NULL,
    result       VARCHAR2(10) NOT NULL CHECK (result IN ('成功','失败')),
    fail_reason  VARCHAR2(100)
);

CREATE TABLE operation_log (
    log_id        NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    module        VARCHAR2(50) NOT NULL,
    action        VARCHAR2(50) NOT NULL,
    operator_id   NUMBER(10) NOT NULL REFERENCES sys_user(user_id),
    operate_time  TIMESTAMP  NOT NULL,
    ip_address    VARCHAR2(45),
    before_data   CLOB CHECK (before_data IS JSON),
    after_data    CLOB CHECK (after_data IS JSON)
);

-- ---------- 2. 物料与BOM管理模块 ----------

CREATE TABLE material_category (
    category_id    NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    category_name  VARCHAR2(50) NOT NULL
);

CREATE TABLE supplier (
    supplier_id     NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    supplier_name   VARCHAR2(100) NOT NULL,
    contact_person  VARCHAR2(50),
    contact_phone   VARCHAR2(20)
);

-- material 与 bom_version 存在循环外键，current_version_id 的 FK 在两表建成后 ALTER 添加
CREATE TABLE material (
    material_id          NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    material_name        VARCHAR2(100) NOT NULL,
    material_type        VARCHAR2(20)  NOT NULL
                         CHECK (material_type IN ('原材料','半成品','成品','辅料')),
    model                VARCHAR2(50),
    unit                 VARCHAR2(10)  NOT NULL,
    category_id          NUMBER(10) NOT NULL REFERENCES material_category(category_id),
    safety_stock         NUMBER(12,2) DEFAULT 0 NOT NULL CHECK (safety_stock >= 0),
    default_supplier_id  NUMBER(10) REFERENCES supplier(supplier_id),
    current_version_id   NUMBER(10),
    created_by           NUMBER(10) NOT NULL REFERENCES sys_user(user_id),
    created_time         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_time         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE bom_version (
    version_id      NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    material_id     NUMBER(10) NOT NULL REFERENCES material(material_id),
    version_no      VARCHAR2(20) NOT NULL,
    effective_date  DATE NOT NULL,
    expire_date     DATE,
    change_reason   VARCHAR2(200),
    created_by      NUMBER(10) NOT NULL REFERENCES sys_user(user_id),
    CONSTRAINT uk_bom_version UNIQUE (material_id, version_no),
    CONSTRAINT ck_version_date CHECK (expire_date IS NULL OR expire_date >= effective_date)
);

ALTER TABLE material ADD CONSTRAINT fk_material_cur_ver
    FOREIGN KEY (current_version_id) REFERENCES bom_version(version_id);

CREATE TABLE material_stock (
    material_id    NUMBER(10) PRIMARY KEY REFERENCES material(material_id),
    available_qty  NUMBER(12,2) DEFAULT 0 NOT NULL CHECK (available_qty >= 0),
    locked_qty     NUMBER(12,2) DEFAULT 0 NOT NULL CHECK (locked_qty >= 0),
    last_in_date   TIMESTAMP,
    last_out_date  TIMESTAMP
);

CREATE TABLE bom (
    bom_id              NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    parent_material_id  NUMBER(10) NOT NULL REFERENCES material(material_id),
    child_material_id   NUMBER(10) NOT NULL REFERENCES material(material_id),
    version_id          NUMBER(10) NOT NULL REFERENCES bom_version(version_id),
    quantity            NUMBER(10,4) NOT NULL CHECK (quantity > 0),
    loss_rate           NUMBER(5,4)  DEFAULT 0 NOT NULL
                        CHECK (loss_rate >= 0 AND loss_rate < 1),
    CONSTRAINT uk_bom UNIQUE (version_id, parent_material_id, child_material_id),
    CONSTRAINT ck_bom_no_self CHECK (parent_material_id <> child_material_id)
);

CREATE TABLE demand_analysis (
    analysis_id     NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    material_id     NUMBER(10) NOT NULL REFERENCES material(material_id),
    version_id      NUMBER(10) NOT NULL REFERENCES bom_version(version_id),
    production_qty  NUMBER(12,2) NOT NULL CHECK (production_qty > 0),
    demand_detail   CLOB CHECK (demand_detail IS JSON),
    analysis_time   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- ---------- 3. 采购管理模块 ----------

CREATE TABLE purchase_order (
    order_id       NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    supplier_id    NUMBER(10) NOT NULL REFERENCES supplier(supplier_id),
    status         VARCHAR2(20) NOT NULL
                   CHECK (status IN ('草稿','已提交','部分到货','已完成','已取消')),
    order_date     DATE NOT NULL,
    expected_date  DATE NOT NULL,
    actual_date    DATE,
    buyer_id       NUMBER(10) NOT NULL REFERENCES sys_user(user_id),
    total_amount   NUMBER(14,2) DEFAULT 0 NOT NULL   -- 反范式派生列，由应用层维护
);

CREATE TABLE purchase_order_item (
    item_id       NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    order_id      NUMBER(10) NOT NULL REFERENCES purchase_order(order_id),
    material_id   NUMBER(10) NOT NULL REFERENCES material(material_id),
    quantity      NUMBER(12,2) NOT NULL CHECK (quantity > 0),
    received_qty  NUMBER(12,2) DEFAULT 0 NOT NULL CHECK (received_qty >= 0),
    unit_price    NUMBER(10,2) NOT NULL CHECK (unit_price >= 0)
);

CREATE TABLE overdue_reminder (
    reminder_id    NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    order_id       NUMBER(10) NOT NULL REFERENCES purchase_order(order_id),
    expected_date  DATE NOT NULL,          -- 提醒生成时点快照
    overdue_days   NUMBER(6) NOT NULL CHECK (overdue_days > 0),
    remind_time    TIMESTAMP NOT NULL,
    status         VARCHAR2(20) NOT NULL
                   CHECK (status IN ('待催交','已催交','已到货')),
    remark         VARCHAR2(200)
);

CREATE TABLE receive_record (
    receive_id    NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    order_id      NUMBER(10) NOT NULL REFERENCES purchase_order(order_id),
    material_id   NUMBER(10) NOT NULL REFERENCES material(material_id),
    quantity      NUMBER(12,2) NOT NULL CHECK (quantity > 0),
    receive_date  DATE NOT NULL
);

-- 报价表：修正文档 3-35 的字段错误（原 operator_id number(12,2) 应为报价 price），
-- 并按需求描述补充有效期字段
CREATE TABLE supplier_price (
    id           NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    supplier     NUMBER(10) NOT NULL REFERENCES supplier(supplier_id),
    material     NUMBER(10) NOT NULL REFERENCES material(material_id),
    price        NUMBER(12,2) NOT NULL CHECK (price >= 0),
    valid_from   DATE NOT NULL,
    valid_to     DATE,
    CONSTRAINT uk_supplier_price UNIQUE (supplier, material, valid_from)
);

-- ---------- 4. 生产管理模块 ----------

CREATE TABLE line_type (
    type_id    NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    type_name  VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE production_line (
    line_id     NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    type_id     NUMBER(10) NOT NULL REFERENCES line_type(type_id),
    start_date  DATE NOT NULL,
    manager_id  NUMBER(10) NOT NULL REFERENCES sys_user(user_id)
);

CREATE TABLE capacity_config (
    config_id    NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    material_id  NUMBER(10) NOT NULL REFERENCES material(material_id),
    type_id      NUMBER(10) NOT NULL REFERENCES line_type(type_id),
    unit_time    NUMBER(8,2) NOT NULL CHECK (unit_time > 0),   -- 分钟/件
    CONSTRAINT uk_capacity_config UNIQUE (material_id, type_id)
);

CREATE TABLE production_calendar (
    calendar_date  DATE NOT NULL,
    line_id        NUMBER(10) NOT NULL REFERENCES production_line(line_id),
    config_id      NUMBER(10) NOT NULL REFERENCES capacity_config(config_id),
    CONSTRAINT pk_prod_calendar PRIMARY KEY (calendar_date, line_id)
);

CREATE TABLE production_order (
    order_id      NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    material_id   NUMBER(10) NOT NULL REFERENCES material(material_id),
    version_id    NUMBER(10) NOT NULL REFERENCES bom_version(version_id),
    plan_qty      NUMBER(12,2) NOT NULL CHECK (plan_qty > 0),
    finished_qty  NUMBER(12,2) DEFAULT 0 NOT NULL CHECK (finished_qty >= 0),
    plan_start    DATE NOT NULL,
    plan_end      DATE NOT NULL,
    actual_start  DATE,
    actual_end    DATE,
    status        VARCHAR2(20) NOT NULL
                  CHECK (status IN ('待审核','待排产','生产中','已完工','已取消')),
    CONSTRAINT ck_po_plan_date CHECK (plan_end >= plan_start)
);

CREATE TABLE external_order (
    ext_order_id    NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    customer_id     NUMBER(10) NOT NULL REFERENCES sys_user(user_id),
    material_id     NUMBER(10) NOT NULL REFERENCES material(material_id),
    quantity        NUMBER(12,2) NOT NULL CHECK (quantity > 0),
    expected_date   DATE NOT NULL,
    contact_person  VARCHAR2(50) NOT NULL,
    contact_phone   VARCHAR2(20) NOT NULL,
    status          VARCHAR2(20) NOT NULL
                    CHECK (status IN ('待审核','已接受','已拒绝')),
    submit_time     TIMESTAMP NOT NULL,
    review_comment  VARCHAR2(200)
);

CREATE TABLE external_order_production (
    ext_order_id  NUMBER(10) NOT NULL REFERENCES external_order(ext_order_id),
    order_id      NUMBER(10) NOT NULL REFERENCES production_order(order_id),
    CONSTRAINT pk_ext_prod PRIMARY KEY (ext_order_id, order_id)
);

CREATE TABLE capacity_detection (
    detection_id     NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    line_id          NUMBER(10) NOT NULL REFERENCES production_line(line_id),
    period_start     TIMESTAMP NOT NULL,
    period_end       TIMESTAMP NOT NULL,
    plan_capacity    NUMBER(12,2) NOT NULL,
    actual_capacity  NUMBER(12,2) NOT NULL,
    diff_qty         NUMBER(12,2) NOT NULL,
    diff_rate        NUMBER(5,4)  NOT NULL,
    reason_type      VARCHAR2(50)
);

CREATE TABLE capacity_balance (
    balance_id       NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    before_plan      CLOB CHECK (before_plan IS JSON),
    after_plan       CLOB CHECK (after_plan IS JSON),
    operator_id      NUMBER(10) NOT NULL REFERENCES sys_user(user_id),
    adjust_time      TIMESTAMP NOT NULL,
    affected_orders  CLOB CHECK (affected_orders IS JSON)
);

CREATE TABLE fault_record (
    fault_id      NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    line_id       NUMBER(10) NOT NULL REFERENCES production_line(line_id),
    fault_type    VARCHAR2(50) NOT NULL,
    description   VARCHAR2(500),
    occur_time    TIMESTAMP NOT NULL,
    recover_time  TIMESTAMP,
    status        VARCHAR2(20) NOT NULL
                  CHECK (status IN ('待维修','维修中','已恢复')),
    reporter_id   NUMBER(10) NOT NULL REFERENCES sys_user(user_id),
    repairer_id   NUMBER(10) REFERENCES sys_user(user_id)
);

CREATE TABLE line_status (
    line_id              NUMBER(10) PRIMARY KEY REFERENCES production_line(line_id),
    status               VARCHAR2(20) NOT NULL
                         CHECK (status IN ('空闲','运行','故障')),
    current_order_id     NUMBER(10) REFERENCES production_order(order_id),
    current_material_id  NUMBER(10) REFERENCES material(material_id),  -- 冗余快照列
    finished_qty         NUMBER(12,2) DEFAULT 0 NOT NULL,
    efficiency           NUMBER(5,4),
    updated_time         TIMESTAMP NOT NULL
);

-- ---------- 5. 库存管理模块 ----------

CREATE TABLE stock_alert (
    alert_id       NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    material_id    NUMBER(10) NOT NULL REFERENCES material(material_id),
    alert_type     VARCHAR2(20) DEFAULT '低库存' NOT NULL,
    available_qty  NUMBER(12,2) NOT NULL,   -- 触发时点快照
    threshold      NUMBER(12,2) NOT NULL,   -- 触发时点快照
    alert_time     TIMESTAMP NOT NULL,
    status         VARCHAR2(20) NOT NULL
                   CHECK (status IN ('待处理','已处理','已忽略')),
    handler_id     NUMBER(10) REFERENCES sys_user(user_id),
    handle_time    TIMESTAMP
);

CREATE TABLE stock_lock (
    lock_id       NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    order_id      NUMBER(10) NOT NULL REFERENCES production_order(order_id),
    material_id   NUMBER(10) NOT NULL REFERENCES material(material_id),
    lock_qty      NUMBER(12,2) NOT NULL CHECK (lock_qty > 0),
    status        VARCHAR2(20) NOT NULL
                  CHECK (status IN ('已锁定','已取消','已消耗')),
    lock_time     TIMESTAMP NOT NULL,
    release_time  TIMESTAMP,
    operator_id   NUMBER(10) NOT NULL REFERENCES sys_user(user_id)
);

CREATE TABLE waste_detection (
    detection_id   NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    material_id    NUMBER(10) NOT NULL REFERENCES material(material_id),
    detect_time    TIMESTAMP NOT NULL,
    available_qty  NUMBER(12,2) NOT NULL,
    last_out_date  DATE,
    idle_days      NUMBER(6) NOT NULL,
    status         VARCHAR2(20) NOT NULL
                   CHECK (status IN ('待处理','已处理','已忽略')),
    handler_id     NUMBER(10) REFERENCES sys_user(user_id)
);

CREATE TABLE finish_inbound (
    inbound_id     NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    order_id       NUMBER(10) NOT NULL REFERENCES production_order(order_id),
    material_id    NUMBER(10) NOT NULL REFERENCES material(material_id),   -- 入库时点快照
    version_id     NUMBER(10) NOT NULL REFERENCES bom_version(version_id), -- 入库时点快照
    finish_qty     NUMBER(12,2) NOT NULL CHECK (finish_qty > 0),
    qualified_qty  NUMBER(12,2) NOT NULL CHECK (qualified_qty >= 0),
    batch_no       VARCHAR2(30) NOT NULL,
    inbound_time   TIMESTAMP NOT NULL,
    operator_id    NUMBER(10) NOT NULL REFERENCES sys_user(user_id),
    CONSTRAINT ck_inbound_qty CHECK (qualified_qty <= finish_qty)
);

-- ---------- 6. 质量追溯模块 ----------

CREATE TABLE batch_consumption (
    consumption_id  NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    order_id        NUMBER(10) NOT NULL REFERENCES production_order(order_id),
    item_id         NUMBER(10) NOT NULL REFERENCES purchase_order_item(item_id),
    consume_qty     NUMBER(12,2) NOT NULL CHECK (consume_qty > 0)
);

-- ---------- 7. 常用检索索引（对应文档 1.1.2 索引要求） ----------

CREATE INDEX idx_material_name      ON material(material_name);
CREATE INDEX idx_material_type      ON material(material_type);
CREATE INDEX idx_material_category  ON material(category_id);
CREATE INDEX idx_bom_parent         ON bom(parent_material_id, version_id);
CREATE INDEX idx_bom_child          ON bom(child_material_id, version_id);
CREATE INDEX idx_po_supplier        ON purchase_order(supplier_id, status);
CREATE INDEX idx_po_expected        ON purchase_order(expected_date);
CREATE INDEX idx_poi_material       ON purchase_order_item(material_id);
CREATE INDEX idx_prod_order_status  ON production_order(status, material_id);
CREATE INDEX idx_lock_order         ON stock_lock(order_id, status);
CREATE INDEX idx_alert_material     ON stock_alert(material_id, status);
CREATE INDEX idx_bc_order           ON batch_consumption(order_id);
CREATE INDEX idx_bc_item            ON batch_consumption(item_id);
CREATE INDEX idx_oplog_time         ON operation_log(operate_time);
