/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class BatchConsumptionPageResponseAllOfData : IEquatable<BatchConsumptionPageResponseAllOfData>
    {
        /// <summary>
        /// 数据总数。
        /// </summary>
        /// <value>数据总数。</value>
        /* <example>25</example> */
        [Required]
        [DataMember(Name="total", EmitDefaultValue=true)]
        public int Total { get; set; }

        /// <summary>
        /// 当前页码。
        /// </summary>
        /// <value>当前页码。</value>
        /* <example>1</example> */
        [Required]
        [DataMember(Name="page", EmitDefaultValue=true)]
        public int Page { get; set; }

        /// <summary>
        /// 每页数据数量。
        /// </summary>
        /// <value>每页数据数量。</value>
        /* <example>10</example> */
        [Required]
        [DataMember(Name="page_size", EmitDefaultValue=true)]
        public int PageSize { get; set; }

        /// <summary>
        /// Gets or Sets Records
        /// </summary>
        [Required]
        [DataMember(Name="records", EmitDefaultValue=false)]
        public List<BatchConsumption> Records { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BatchConsumptionPageResponseAllOfData {\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  Page: ").Append(Page).Append("\n");
            sb.Append("  PageSize: ").Append(PageSize).Append("\n");
            sb.Append("  Records: ").Append(Records).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((BatchConsumptionPageResponseAllOfData)obj);
        }

        /// <summary>
        /// Returns true if BatchConsumptionPageResponseAllOfData instances are equal
        /// </summary>
        /// <param name="other">Instance of BatchConsumptionPageResponseAllOfData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BatchConsumptionPageResponseAllOfData other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Total == other.Total ||
                    
                    Total.Equals(other.Total)
                ) && 
                (
                    Page == other.Page ||
                    
                    Page.Equals(other.Page)
                ) && 
                (
                    PageSize == other.PageSize ||
                    
                    PageSize.Equals(other.PageSize)
                ) && 
                (
                    Records == other.Records ||
                    Records != null &&
                    other.Records != null &&
                    Records.SequenceEqual(other.Records)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + Total.GetHashCode();
                    
                    hashCode = hashCode * 59 + Page.GetHashCode();
                    
                    hashCode = hashCode * 59 + PageSize.GetHashCode();
                    if (Records != null)
                    hashCode = hashCode * 59 + Records.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(BatchConsumptionPageResponseAllOfData left, BatchConsumptionPageResponseAllOfData right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(BatchConsumptionPageResponseAllOfData left, BatchConsumptionPageResponseAllOfData right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
