/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Bom : IEquatable<Bom>
    {
        /// <summary>
        /// Gets or Sets BomId
        /// </summary>
        [DataMember(Name="bom_id", EmitDefaultValue=true)]
        public int BomId { get; set; }

        /// <summary>
        /// Gets or Sets ParentMaterialId
        /// </summary>
        [DataMember(Name="parent_material_id", EmitDefaultValue=true)]
        public int ParentMaterialId { get; set; }

        /// <summary>
        /// Gets or Sets ChildMaterialId
        /// </summary>
        [DataMember(Name="child_material_id", EmitDefaultValue=true)]
        public int ChildMaterialId { get; set; }

        /// <summary>
        /// Gets or Sets VersionId
        /// </summary>
        [DataMember(Name="version_id", EmitDefaultValue=true)]
        public int VersionId { get; set; }

        /// <summary>
        /// Gets or Sets Quantity
        /// </summary>
        [DataMember(Name="quantity", EmitDefaultValue=true)]
        public double Quantity { get; set; }

        /// <summary>
        /// Gets or Sets LossRate
        /// </summary>
        [DataMember(Name="loss_rate", EmitDefaultValue=true)]
        public double LossRate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Bom {\n");
            sb.Append("  BomId: ").Append(BomId).Append("\n");
            sb.Append("  ParentMaterialId: ").Append(ParentMaterialId).Append("\n");
            sb.Append("  ChildMaterialId: ").Append(ChildMaterialId).Append("\n");
            sb.Append("  VersionId: ").Append(VersionId).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  LossRate: ").Append(LossRate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Bom)obj);
        }

        /// <summary>
        /// Returns true if Bom instances are equal
        /// </summary>
        /// <param name="other">Instance of Bom to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Bom other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    BomId == other.BomId ||
                    
                    BomId.Equals(other.BomId)
                ) && 
                (
                    ParentMaterialId == other.ParentMaterialId ||
                    
                    ParentMaterialId.Equals(other.ParentMaterialId)
                ) && 
                (
                    ChildMaterialId == other.ChildMaterialId ||
                    
                    ChildMaterialId.Equals(other.ChildMaterialId)
                ) && 
                (
                    VersionId == other.VersionId ||
                    
                    VersionId.Equals(other.VersionId)
                ) && 
                (
                    Quantity == other.Quantity ||
                    
                    Quantity.Equals(other.Quantity)
                ) && 
                (
                    LossRate == other.LossRate ||
                    
                    LossRate.Equals(other.LossRate)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + BomId.GetHashCode();
                    
                    hashCode = hashCode * 59 + ParentMaterialId.GetHashCode();
                    
                    hashCode = hashCode * 59 + ChildMaterialId.GetHashCode();
                    
                    hashCode = hashCode * 59 + VersionId.GetHashCode();
                    
                    hashCode = hashCode * 59 + Quantity.GetHashCode();
                    
                    hashCode = hashCode * 59 + LossRate.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Bom left, Bom right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Bom left, Bom right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
