/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// BOM 循环依赖检查结果，由后端根据指定版本内的父子物料关系递归计算得到。
    /// </summary>
    [DataContract]
    public partial class BomCycleCheckResult : IEquatable<BomCycleCheckResult>
    {
        /// <summary>
        /// 是否存在循环依赖，由后端递归检查 BOM 父子关系得到。
        /// </summary>
        /// <value>是否存在循环依赖，由后端递归检查 BOM 父子关系得到。</value>
        [DataMember(Name="has_cycle", EmitDefaultValue=true)]
        public bool HasCycle { get; set; }

        /// <summary>
        /// 形成循环依赖时的物料编号路径；无循环依赖时返回空数组。
        /// </summary>
        /// <value>形成循环依赖时的物料编号路径；无循环依赖时返回空数组。</value>
        [DataMember(Name="cycle_path", EmitDefaultValue=false)]
        public List<int> CyclePath { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BomCycleCheckResult {\n");
            sb.Append("  HasCycle: ").Append(HasCycle).Append("\n");
            sb.Append("  CyclePath: ").Append(CyclePath).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((BomCycleCheckResult)obj);
        }

        /// <summary>
        /// Returns true if BomCycleCheckResult instances are equal
        /// </summary>
        /// <param name="other">Instance of BomCycleCheckResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BomCycleCheckResult other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    HasCycle == other.HasCycle ||
                    
                    HasCycle.Equals(other.HasCycle)
                ) && 
                (
                    CyclePath == other.CyclePath ||
                    CyclePath != null &&
                    other.CyclePath != null &&
                    CyclePath.SequenceEqual(other.CyclePath)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + HasCycle.GetHashCode();
                    if (CyclePath != null)
                    hashCode = hashCode * 59 + CyclePath.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(BomCycleCheckResult left, BomCycleCheckResult right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(BomCycleCheckResult left, BomCycleCheckResult right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
