/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// BOM 层级树节点，由后端按照指定产品和 BOM 版本递归展开计算得到。
    /// </summary>
    [DataContract]
    public partial class BomTreeNode : IEquatable<BomTreeNode>
    {
        /// <summary>
        /// 物料编号，来源于 material.material_id。
        /// </summary>
        /// <value>物料编号，来源于 material.material_id。</value>
        [DataMember(Name="material_id", EmitDefaultValue=true)]
        public int MaterialId { get; set; }

        /// <summary>
        /// 物料名称，来源于 material.material_name。
        /// </summary>
        /// <value>物料名称，来源于 material.material_name。</value>
        [DataMember(Name="material_name", EmitDefaultValue=false)]
        public string MaterialName { get; set; }

        /// <summary>
        /// 型号规格，来源于 material.model。
        /// </summary>
        /// <value>型号规格，来源于 material.model。</value>
        [DataMember(Name="model", EmitDefaultValue=false)]
        public string Model { get; set; }

        /// <summary>
        /// 物料类型，来源于 material.material_type。
        /// </summary>
        /// <value>物料类型，来源于 material.material_type。</value>
        [DataMember(Name="material_type", EmitDefaultValue=false)]
        public string MaterialType { get; set; }

        /// <summary>
        /// 计量单位，来源于 material.unit。
        /// </summary>
        /// <value>计量单位，来源于 material.unit。</value>
        [DataMember(Name="unit", EmitDefaultValue=false)]
        public string Unit { get; set; }

        /// <summary>
        /// 相对父节点的单位用量，来源于 bom.quantity。
        /// </summary>
        /// <value>相对父节点的单位用量，来源于 bom.quantity。</value>
        [DataMember(Name="quantity", EmitDefaultValue=true)]
        public double Quantity { get; set; }

        /// <summary>
        /// 相对根产品的累计用量，由后端按路径上各层 quantity 乘积计算得到。
        /// </summary>
        /// <value>相对根产品的累计用量，由后端按路径上各层 quantity 乘积计算得到。</value>
        [DataMember(Name="accumulated_quantity", EmitDefaultValue=true)]
        public double AccumulatedQuantity { get; set; }

        /// <summary>
        /// 节点层级，由后端递归展开时计算，根节点为 0。
        /// </summary>
        /// <value>节点层级，由后端递归展开时计算，根节点为 0。</value>
        [DataMember(Name="depth", EmitDefaultValue=true)]
        public int Depth { get; set; }

        /// <summary>
        /// 父物料编号，根节点返回 null。
        /// </summary>
        /// <value>父物料编号，根节点返回 null。</value>
        [DataMember(Name="parent_material_id", EmitDefaultValue=true)]
        public int? ParentMaterialId { get; set; }

        /// <summary>
        /// 从根节点到当前节点的物料编号路径，由后端递归拼接得到。
        /// </summary>
        /// <value>从根节点到当前节点的物料编号路径，由后端递归拼接得到。</value>
        [DataMember(Name="path", EmitDefaultValue=false)]
        public string Path { get; set; }

        /// <summary>
        /// 是否叶子节点，由后端根据当前物料是否还有子项 BOM 判断。
        /// </summary>
        /// <value>是否叶子节点，由后端根据当前物料是否还有子项 BOM 判断。</value>
        [DataMember(Name="is_leaf", EmitDefaultValue=true)]
        public bool IsLeaf { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BomTreeNode {\n");
            sb.Append("  MaterialId: ").Append(MaterialId).Append("\n");
            sb.Append("  MaterialName: ").Append(MaterialName).Append("\n");
            sb.Append("  Model: ").Append(Model).Append("\n");
            sb.Append("  MaterialType: ").Append(MaterialType).Append("\n");
            sb.Append("  Unit: ").Append(Unit).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  AccumulatedQuantity: ").Append(AccumulatedQuantity).Append("\n");
            sb.Append("  Depth: ").Append(Depth).Append("\n");
            sb.Append("  ParentMaterialId: ").Append(ParentMaterialId).Append("\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("  IsLeaf: ").Append(IsLeaf).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((BomTreeNode)obj);
        }

        /// <summary>
        /// Returns true if BomTreeNode instances are equal
        /// </summary>
        /// <param name="other">Instance of BomTreeNode to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BomTreeNode other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    MaterialId == other.MaterialId ||
                    
                    MaterialId.Equals(other.MaterialId)
                ) && 
                (
                    MaterialName == other.MaterialName ||
                    MaterialName != null &&
                    MaterialName.Equals(other.MaterialName)
                ) && 
                (
                    Model == other.Model ||
                    Model != null &&
                    Model.Equals(other.Model)
                ) && 
                (
                    MaterialType == other.MaterialType ||
                    MaterialType != null &&
                    MaterialType.Equals(other.MaterialType)
                ) && 
                (
                    Unit == other.Unit ||
                    Unit != null &&
                    Unit.Equals(other.Unit)
                ) && 
                (
                    Quantity == other.Quantity ||
                    
                    Quantity.Equals(other.Quantity)
                ) && 
                (
                    AccumulatedQuantity == other.AccumulatedQuantity ||
                    
                    AccumulatedQuantity.Equals(other.AccumulatedQuantity)
                ) && 
                (
                    Depth == other.Depth ||
                    
                    Depth.Equals(other.Depth)
                ) && 
                (
                    ParentMaterialId == other.ParentMaterialId ||
                    ParentMaterialId != null &&
                    ParentMaterialId.Equals(other.ParentMaterialId)
                ) && 
                (
                    Path == other.Path ||
                    Path != null &&
                    Path.Equals(other.Path)
                ) && 
                (
                    IsLeaf == other.IsLeaf ||
                    
                    IsLeaf.Equals(other.IsLeaf)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + MaterialId.GetHashCode();
                    if (MaterialName != null)
                    hashCode = hashCode * 59 + MaterialName.GetHashCode();
                    if (Model != null)
                    hashCode = hashCode * 59 + Model.GetHashCode();
                    if (MaterialType != null)
                    hashCode = hashCode * 59 + MaterialType.GetHashCode();
                    if (Unit != null)
                    hashCode = hashCode * 59 + Unit.GetHashCode();
                    
                    hashCode = hashCode * 59 + Quantity.GetHashCode();
                    
                    hashCode = hashCode * 59 + AccumulatedQuantity.GetHashCode();
                    
                    hashCode = hashCode * 59 + Depth.GetHashCode();
                    if (ParentMaterialId != null)
                    hashCode = hashCode * 59 + ParentMaterialId.GetHashCode();
                    if (Path != null)
                    hashCode = hashCode * 59 + Path.GetHashCode();
                    
                    hashCode = hashCode * 59 + IsLeaf.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(BomTreeNode left, BomTreeNode right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(BomTreeNode left, BomTreeNode right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
