/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 调整人从当前登录用户推导，客户端不得传 operator_id。
    /// </summary>
    [DataContract]
    public partial class CapacityBalanceSaveRequest : IEquatable<CapacityBalanceSaveRequest>
    {
        /// <summary>
        /// Gets or Sets BeforePlan
        /// </summary>
        [Required]
        [DataMember(Name="before_plan", EmitDefaultValue=false)]
        public Dictionary<string, Object> BeforePlan { get; set; }

        /// <summary>
        /// Gets or Sets AfterPlan
        /// </summary>
        [Required]
        [DataMember(Name="after_plan", EmitDefaultValue=false)]
        public Dictionary<string, Object> AfterPlan { get; set; }

        /// <summary>
        /// Gets or Sets AffectedOrders
        /// </summary>
        [Required]
        [DataMember(Name="affected_orders", EmitDefaultValue=false)]
        public List<long> AffectedOrders { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CapacityBalanceSaveRequest {\n");
            sb.Append("  BeforePlan: ").Append(BeforePlan).Append("\n");
            sb.Append("  AfterPlan: ").Append(AfterPlan).Append("\n");
            sb.Append("  AffectedOrders: ").Append(AffectedOrders).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CapacityBalanceSaveRequest)obj);
        }

        /// <summary>
        /// Returns true if CapacityBalanceSaveRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of CapacityBalanceSaveRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CapacityBalanceSaveRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    BeforePlan == other.BeforePlan ||
                    BeforePlan != null &&
                    other.BeforePlan != null &&
                    BeforePlan.SequenceEqual(other.BeforePlan)
                ) && 
                (
                    AfterPlan == other.AfterPlan ||
                    AfterPlan != null &&
                    other.AfterPlan != null &&
                    AfterPlan.SequenceEqual(other.AfterPlan)
                ) && 
                (
                    AffectedOrders == other.AffectedOrders ||
                    AffectedOrders != null &&
                    other.AffectedOrders != null &&
                    AffectedOrders.SequenceEqual(other.AffectedOrders)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (BeforePlan != null)
                    hashCode = hashCode * 59 + BeforePlan.GetHashCode();
                    if (AfterPlan != null)
                    hashCode = hashCode * 59 + AfterPlan.GetHashCode();
                    if (AffectedOrders != null)
                    hashCode = hashCode * 59 + AffectedOrders.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CapacityBalanceSaveRequest left, CapacityBalanceSaveRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CapacityBalanceSaveRequest left, CapacityBalanceSaveRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
