/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CompletionInboundOrder : IEquatable<CompletionInboundOrder>
    {
        /// <summary>
        /// Gets or Sets InboundId
        /// </summary>
        [Required]
        [DataMember(Name="inbound_id", EmitDefaultValue=true)]
        public long InboundId { get; set; }

        /// <summary>
        /// Gets or Sets OrderId
        /// </summary>
        [Required]
        [DataMember(Name="order_id", EmitDefaultValue=true)]
        public long OrderId { get; set; }

        /// <summary>
        /// Gets or Sets MaterialId
        /// </summary>
        [Required]
        [DataMember(Name="material_id", EmitDefaultValue=true)]
        public long MaterialId { get; set; }

        /// <summary>
        /// Gets or Sets ProductName
        /// </summary>
        [DataMember(Name="product_name", EmitDefaultValue=false)]
        public string ProductName { get; set; }

        /// <summary>
        /// Gets or Sets VersionId
        /// </summary>
        [Required]
        [DataMember(Name="version_id", EmitDefaultValue=true)]
        public long VersionId { get; set; }

        /// <summary>
        /// Gets or Sets FinishQty
        /// </summary>
        [Required]
        [DataMember(Name="finish_qty", EmitDefaultValue=true)]
        public decimal FinishQty { get; set; }

        /// <summary>
        /// Gets or Sets QualifiedQty
        /// </summary>
        [Required]
        [DataMember(Name="qualified_qty", EmitDefaultValue=true)]
        public decimal QualifiedQty { get; set; }

        /// <summary>
        /// Gets or Sets BatchNo
        /// </summary>
        [Required]
        [DataMember(Name="batch_no", EmitDefaultValue=false)]
        public string BatchNo { get; set; }

        /// <summary>
        /// Gets or Sets InboundTime
        /// </summary>
        [Required]
        [DataMember(Name="inbound_time", EmitDefaultValue=true)]
        public DateTime InboundTime { get; set; }

        /// <summary>
        /// Gets or Sets OperatorId
        /// </summary>
        [Required]
        [DataMember(Name="operator_id", EmitDefaultValue=true)]
        public long OperatorId { get; set; }

        /// <summary>
        /// Gets or Sets ConsumedLockRecords
        /// </summary>
        [DataMember(Name="consumed_lock_records", EmitDefaultValue=false)]
        public List<StockLockRecord> ConsumedLockRecords { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CompletionInboundOrder {\n");
            sb.Append("  InboundId: ").Append(InboundId).Append("\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  MaterialId: ").Append(MaterialId).Append("\n");
            sb.Append("  ProductName: ").Append(ProductName).Append("\n");
            sb.Append("  VersionId: ").Append(VersionId).Append("\n");
            sb.Append("  FinishQty: ").Append(FinishQty).Append("\n");
            sb.Append("  QualifiedQty: ").Append(QualifiedQty).Append("\n");
            sb.Append("  BatchNo: ").Append(BatchNo).Append("\n");
            sb.Append("  InboundTime: ").Append(InboundTime).Append("\n");
            sb.Append("  OperatorId: ").Append(OperatorId).Append("\n");
            sb.Append("  ConsumedLockRecords: ").Append(ConsumedLockRecords).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CompletionInboundOrder)obj);
        }

        /// <summary>
        /// Returns true if CompletionInboundOrder instances are equal
        /// </summary>
        /// <param name="other">Instance of CompletionInboundOrder to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CompletionInboundOrder other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    InboundId == other.InboundId ||
                    
                    InboundId.Equals(other.InboundId)
                ) && 
                (
                    OrderId == other.OrderId ||
                    
                    OrderId.Equals(other.OrderId)
                ) && 
                (
                    MaterialId == other.MaterialId ||
                    
                    MaterialId.Equals(other.MaterialId)
                ) && 
                (
                    ProductName == other.ProductName ||
                    ProductName != null &&
                    ProductName.Equals(other.ProductName)
                ) && 
                (
                    VersionId == other.VersionId ||
                    
                    VersionId.Equals(other.VersionId)
                ) && 
                (
                    FinishQty == other.FinishQty ||
                    
                    FinishQty.Equals(other.FinishQty)
                ) && 
                (
                    QualifiedQty == other.QualifiedQty ||
                    
                    QualifiedQty.Equals(other.QualifiedQty)
                ) && 
                (
                    BatchNo == other.BatchNo ||
                    BatchNo != null &&
                    BatchNo.Equals(other.BatchNo)
                ) && 
                (
                    InboundTime == other.InboundTime ||
                    
                    InboundTime.Equals(other.InboundTime)
                ) && 
                (
                    OperatorId == other.OperatorId ||
                    
                    OperatorId.Equals(other.OperatorId)
                ) && 
                (
                    ConsumedLockRecords == other.ConsumedLockRecords ||
                    ConsumedLockRecords != null &&
                    other.ConsumedLockRecords != null &&
                    ConsumedLockRecords.SequenceEqual(other.ConsumedLockRecords)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + InboundId.GetHashCode();
                    
                    hashCode = hashCode * 59 + OrderId.GetHashCode();
                    
                    hashCode = hashCode * 59 + MaterialId.GetHashCode();
                    if (ProductName != null)
                    hashCode = hashCode * 59 + ProductName.GetHashCode();
                    
                    hashCode = hashCode * 59 + VersionId.GetHashCode();
                    
                    hashCode = hashCode * 59 + FinishQty.GetHashCode();
                    
                    hashCode = hashCode * 59 + QualifiedQty.GetHashCode();
                    if (BatchNo != null)
                    hashCode = hashCode * 59 + BatchNo.GetHashCode();
                    
                    hashCode = hashCode * 59 + InboundTime.GetHashCode();
                    
                    hashCode = hashCode * 59 + OperatorId.GetHashCode();
                    if (ConsumedLockRecords != null)
                    hashCode = hashCode * 59 + ConsumedLockRecords.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CompletionInboundOrder left, CompletionInboundOrder right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CompletionInboundOrder left, CompletionInboundOrder right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
