/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ConsumedMaterialBatch : IEquatable<ConsumedMaterialBatch>
    {
        /// <summary>
        /// 采购订单明细编号。
        /// </summary>
        /// <value>采购订单明细编号。</value>
        [Required]
        [DataMember(Name="item_id", EmitDefaultValue=true)]
        public long ItemId { get; set; }

        /// <summary>
        /// Gets or Sets MaterialId
        /// </summary>
        [Required]
        [DataMember(Name="material_id", EmitDefaultValue=true)]
        public long MaterialId { get; set; }

        /// <summary>
        /// 跨表展示字段，来源于物料表 material.material_name，通过 purchase_order_item.material_id &#x3D; material.material_id 关联查询得到，权威物料实体由物料与 BOM 模块维护。
        /// </summary>
        /// <value>跨表展示字段，来源于物料表 material.material_name，通过 purchase_order_item.material_id &#x3D; material.material_id 关联查询得到，权威物料实体由物料与 BOM 模块维护。</value>
        [DataMember(Name="material_name", EmitDefaultValue=true)]
        public string MaterialName { get; set; }

        /// <summary>
        /// 跨表字段，来源于采购订单表 purchase_order.supplier_id，通过 purchase_order_item.order_id &#x3D; purchase_order.order_id 关联查询得到。
        /// </summary>
        /// <value>跨表字段，来源于采购订单表 purchase_order.supplier_id，通过 purchase_order_item.order_id &#x3D; purchase_order.order_id 关联查询得到。</value>
        [DataMember(Name="supplier_id", EmitDefaultValue=true)]
        public long? SupplierId { get; set; }

        /// <summary>
        /// 跨表展示字段，来源于供应商表 supplier.supplier_name，通过 purchase_order_item.order_id 关联 purchase_order.supplier_id 后查询得到，权威供应商实体由采购模块维护。
        /// </summary>
        /// <value>跨表展示字段，来源于供应商表 supplier.supplier_name，通过 purchase_order_item.order_id 关联 purchase_order.supplier_id 后查询得到，权威供应商实体由采购模块维护。</value>
        [DataMember(Name="supplier_name", EmitDefaultValue=true)]
        public string SupplierName { get; set; }

        /// <summary>
        /// 采购订单表 purchase_order.order_id，来源于 purchase_order_item.order_id，用于标识该原材料批次所属采购订单。
        /// </summary>
        /// <value>采购订单表 purchase_order.order_id，来源于 purchase_order_item.order_id，用于标识该原材料批次所属采购订单。</value>
        [DataMember(Name="order_id", EmitDefaultValue=true)]
        public long? OrderId { get; set; }

        /// <summary>
        /// 跨表展示字段，来源于到货记录表 receive_record.receive_date，通过 purchase_order_item.order_id 和 material_id 关联查询该批次到货日期。
        /// </summary>
        /// <value>跨表展示字段，来源于到货记录表 receive_record.receive_date，通过 purchase_order_item.order_id 和 material_id 关联查询该批次到货日期。</value>
        [DataMember(Name="receive_date", EmitDefaultValue=true)]
        public DateOnly? ReceiveDate { get; set; }

        /// <summary>
        /// Gets or Sets ConsumeQty
        /// </summary>
        [Required]
        [DataMember(Name="consume_qty", EmitDefaultValue=true)]
        public decimal ConsumeQty { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ConsumedMaterialBatch {\n");
            sb.Append("  ItemId: ").Append(ItemId).Append("\n");
            sb.Append("  MaterialId: ").Append(MaterialId).Append("\n");
            sb.Append("  MaterialName: ").Append(MaterialName).Append("\n");
            sb.Append("  SupplierId: ").Append(SupplierId).Append("\n");
            sb.Append("  SupplierName: ").Append(SupplierName).Append("\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  ReceiveDate: ").Append(ReceiveDate).Append("\n");
            sb.Append("  ConsumeQty: ").Append(ConsumeQty).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ConsumedMaterialBatch)obj);
        }

        /// <summary>
        /// Returns true if ConsumedMaterialBatch instances are equal
        /// </summary>
        /// <param name="other">Instance of ConsumedMaterialBatch to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ConsumedMaterialBatch other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ItemId == other.ItemId ||
                    
                    ItemId.Equals(other.ItemId)
                ) && 
                (
                    MaterialId == other.MaterialId ||
                    
                    MaterialId.Equals(other.MaterialId)
                ) && 
                (
                    MaterialName == other.MaterialName ||
                    MaterialName != null &&
                    MaterialName.Equals(other.MaterialName)
                ) && 
                (
                    SupplierId == other.SupplierId ||
                    SupplierId != null &&
                    SupplierId.Equals(other.SupplierId)
                ) && 
                (
                    SupplierName == other.SupplierName ||
                    SupplierName != null &&
                    SupplierName.Equals(other.SupplierName)
                ) && 
                (
                    OrderId == other.OrderId ||
                    OrderId != null &&
                    OrderId.Equals(other.OrderId)
                ) && 
                (
                    ReceiveDate == other.ReceiveDate ||
                    ReceiveDate != null &&
                    ReceiveDate.Equals(other.ReceiveDate)
                ) && 
                (
                    ConsumeQty == other.ConsumeQty ||
                    
                    ConsumeQty.Equals(other.ConsumeQty)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + ItemId.GetHashCode();
                    
                    hashCode = hashCode * 59 + MaterialId.GetHashCode();
                    if (MaterialName != null)
                    hashCode = hashCode * 59 + MaterialName.GetHashCode();
                    if (SupplierId != null)
                    hashCode = hashCode * 59 + SupplierId.GetHashCode();
                    if (SupplierName != null)
                    hashCode = hashCode * 59 + SupplierName.GetHashCode();
                    if (OrderId != null)
                    hashCode = hashCode * 59 + OrderId.GetHashCode();
                    if (ReceiveDate != null)
                    hashCode = hashCode * 59 + ReceiveDate.GetHashCode();
                    
                    hashCode = hashCode * 59 + ConsumeQty.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ConsumedMaterialBatch left, ConsumedMaterialBatch right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ConsumedMaterialBatch left, ConsumedMaterialBatch right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
