/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CurrentAccessData : IEquatable<CurrentAccessData>
    {
        /// <summary>
        /// Gets or Sets CurrentUser
        /// </summary>
        [Required]
        [DataMember(Name="current_user", EmitDefaultValue=false)]
        public CurrentAccessUser CurrentUser { get; set; }

        /// <summary>
        /// 当前用户全部有效角色，仅用于身份展示和角色管理，不参与前后端授权判断。
        /// </summary>
        /// <value>当前用户全部有效角色，仅用于身份展示和角色管理，不参与前后端授权判断。</value>
        [Required]
        [DataMember(Name="roles", EmitDefaultValue=false)]
        public List<RoleBrief> Roles { get; set; }

        /// <summary>
        /// 当前用户全部有效角色关联权限码的并集。无有效角色或角色均未配置权限时为空数组。
        /// </summary>
        /// <value>当前用户全部有效角色关联权限码的并集。无有效角色或角色均未配置权限时为空数组。</value>
        [Required]
        [DataMember(Name="permission_codes", EmitDefaultValue=false)]
        public List<PermissionCode> PermissionCodes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CurrentAccessData {\n");
            sb.Append("  CurrentUser: ").Append(CurrentUser).Append("\n");
            sb.Append("  Roles: ").Append(Roles).Append("\n");
            sb.Append("  PermissionCodes: ").Append(PermissionCodes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CurrentAccessData)obj);
        }

        /// <summary>
        /// Returns true if CurrentAccessData instances are equal
        /// </summary>
        /// <param name="other">Instance of CurrentAccessData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CurrentAccessData other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    CurrentUser == other.CurrentUser ||
                    CurrentUser != null &&
                    CurrentUser.Equals(other.CurrentUser)
                ) && 
                (
                    Roles == other.Roles ||
                    Roles != null &&
                    other.Roles != null &&
                    Roles.SequenceEqual(other.Roles)
                ) && 
                (
                    PermissionCodes == other.PermissionCodes ||
                    PermissionCodes != null &&
                    other.PermissionCodes != null &&
                    PermissionCodes.SequenceEqual(other.PermissionCodes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (CurrentUser != null)
                    hashCode = hashCode * 59 + CurrentUser.GetHashCode();
                    if (Roles != null)
                    hashCode = hashCode * 59 + Roles.GetHashCode();
                    if (PermissionCodes != null)
                    hashCode = hashCode * 59 + PermissionCodes.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CurrentAccessData left, CurrentAccessData right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CurrentAccessData left, CurrentAccessData right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
