/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 当前登录者的最小身份信息，不包含密码哈希或联系方式。
    /// </summary>
    [DataContract]
    public partial class CurrentAccessUser : IEquatable<CurrentAccessUser>
    {
        /// <summary>
        /// 当前登录用户的唯一编号。
        /// </summary>
        /// <value>当前登录用户的唯一编号。</value>
        [Required]
        [DataMember(Name="user_id", EmitDefaultValue=true)]
        public long UserId { get; set; }

        /// <summary>
        /// 根据 JWT 身份查询得到的当前用户工号。
        /// </summary>
        /// <value>根据 JWT 身份查询得到的当前用户工号。</value>
        [Required]
        [DataMember(Name="employee_no", EmitDefaultValue=false)]
        public string EmployeeNo { get; set; }

        /// <summary>
        /// 当前用户姓名。
        /// </summary>
        /// <value>当前用户姓名。</value>
        [Required]
        [DataMember(Name="user_name", EmitDefaultValue=false)]
        public string UserName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CurrentAccessUser {\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  EmployeeNo: ").Append(EmployeeNo).Append("\n");
            sb.Append("  UserName: ").Append(UserName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CurrentAccessUser)obj);
        }

        /// <summary>
        /// Returns true if CurrentAccessUser instances are equal
        /// </summary>
        /// <param name="other">Instance of CurrentAccessUser to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CurrentAccessUser other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    UserId == other.UserId ||
                    
                    UserId.Equals(other.UserId)
                ) && 
                (
                    EmployeeNo == other.EmployeeNo ||
                    EmployeeNo != null &&
                    EmployeeNo.Equals(other.EmployeeNo)
                ) && 
                (
                    UserName == other.UserName ||
                    UserName != null &&
                    UserName.Equals(other.UserName)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + UserId.GetHashCode();
                    if (EmployeeNo != null)
                    hashCode = hashCode * 59 + EmployeeNo.GetHashCode();
                    if (UserName != null)
                    hashCode = hashCode * 59 + UserName.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CurrentAccessUser left, CurrentAccessUser right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CurrentAccessUser left, CurrentAccessUser right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
