/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 外部客户自提交订单时 customer_id 从登录态推导；管理员代录时可传 customer_id。
    /// </summary>
    [DataContract]
    public partial class ExternalOrderCreateRequest : IEquatable<ExternalOrderCreateRequest>
    {
        /// <summary>
        /// 使用 external-order:create-own 提交时不得传，由当前登录用户推导；具备 external-order:create-for-customer 时可传，后端必须按权限校验。
        /// </summary>
        /// <value>使用 external-order:create-own 提交时不得传，由当前登录用户推导；具备 external-order:create-for-customer 时可传，后端必须按权限校验。</value>
        [DataMember(Name="customer_id", EmitDefaultValue=true)]
        public long? CustomerId { get; set; }

        /// <summary>
        /// Gets or Sets MaterialId
        /// </summary>
        [Required]
        [DataMember(Name="material_id", EmitDefaultValue=true)]
        public long MaterialId { get; set; }

        /// <summary>
        /// Gets or Sets Quantity
        /// </summary>
        [Required]
        [DataMember(Name="quantity", EmitDefaultValue=true)]
        public decimal Quantity { get; set; }

        /// <summary>
        /// Gets or Sets ExpectedDate
        /// </summary>
        [Required]
        [DataMember(Name="expected_date", EmitDefaultValue=true)]
        public DateOnly ExpectedDate { get; set; }

        /// <summary>
        /// Gets or Sets ContactPerson
        /// </summary>
        [Required]
        [DataMember(Name="contact_person", EmitDefaultValue=false)]
        public string ContactPerson { get; set; }

        /// <summary>
        /// Gets or Sets ContactPhone
        /// </summary>
        [Required]
        [DataMember(Name="contact_phone", EmitDefaultValue=false)]
        public string ContactPhone { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ExternalOrderCreateRequest {\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("  MaterialId: ").Append(MaterialId).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  ExpectedDate: ").Append(ExpectedDate).Append("\n");
            sb.Append("  ContactPerson: ").Append(ContactPerson).Append("\n");
            sb.Append("  ContactPhone: ").Append(ContactPhone).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ExternalOrderCreateRequest)obj);
        }

        /// <summary>
        /// Returns true if ExternalOrderCreateRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of ExternalOrderCreateRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ExternalOrderCreateRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    CustomerId == other.CustomerId ||
                    CustomerId != null &&
                    CustomerId.Equals(other.CustomerId)
                ) && 
                (
                    MaterialId == other.MaterialId ||
                    
                    MaterialId.Equals(other.MaterialId)
                ) && 
                (
                    Quantity == other.Quantity ||
                    
                    Quantity.Equals(other.Quantity)
                ) && 
                (
                    ExpectedDate == other.ExpectedDate ||
                    
                    ExpectedDate.Equals(other.ExpectedDate)
                ) && 
                (
                    ContactPerson == other.ContactPerson ||
                    ContactPerson != null &&
                    ContactPerson.Equals(other.ContactPerson)
                ) && 
                (
                    ContactPhone == other.ContactPhone ||
                    ContactPhone != null &&
                    ContactPhone.Equals(other.ContactPhone)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (CustomerId != null)
                    hashCode = hashCode * 59 + CustomerId.GetHashCode();
                    
                    hashCode = hashCode * 59 + MaterialId.GetHashCode();
                    
                    hashCode = hashCode * 59 + Quantity.GetHashCode();
                    
                    hashCode = hashCode * 59 + ExpectedDate.GetHashCode();
                    if (ContactPerson != null)
                    hashCode = hashCode * 59 + ContactPerson.GetHashCode();
                    if (ContactPhone != null)
                    hashCode = hashCode * 59 + ContactPhone.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ExternalOrderCreateRequest left, ExternalOrderCreateRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ExternalOrderCreateRequest left, ExternalOrderCreateRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
