/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class FaultRecord : IEquatable<FaultRecord>
    {
        /// <summary>
        /// Gets or Sets FaultId
        /// </summary>
        [Required]
        [DataMember(Name="fault_id", EmitDefaultValue=true)]
        public long FaultId { get; set; }

        /// <summary>
        /// Gets or Sets LineId
        /// </summary>
        [Required]
        [DataMember(Name="line_id", EmitDefaultValue=true)]
        public long LineId { get; set; }

        /// <summary>
        /// Gets or Sets FaultType
        /// </summary>
        /* <example>mechanical_fault</example> */
        [Required]
        [DataMember(Name="fault_type", EmitDefaultValue=false)]
        public string FaultType { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [Required]
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets OccurTime
        /// </summary>
        [Required]
        [DataMember(Name="occur_time", EmitDefaultValue=true)]
        public DateTime OccurTime { get; set; }

        /// <summary>
        /// Gets or Sets RecoverTime
        /// </summary>
        [DataMember(Name="recover_time", EmitDefaultValue=true)]
        public DateTime? RecoverTime { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [Required]
        [DataMember(Name="status", EmitDefaultValue=true)]
        public FaultStatus Status { get; set; }

        /// <summary>
        /// Gets or Sets ReporterId
        /// </summary>
        [Required]
        [DataMember(Name="reporter_id", EmitDefaultValue=true)]
        public long ReporterId { get; set; }

        /// <summary>
        /// Gets or Sets RepairerId
        /// </summary>
        [DataMember(Name="repairer_id", EmitDefaultValue=true)]
        public long? RepairerId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FaultRecord {\n");
            sb.Append("  FaultId: ").Append(FaultId).Append("\n");
            sb.Append("  LineId: ").Append(LineId).Append("\n");
            sb.Append("  FaultType: ").Append(FaultType).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  OccurTime: ").Append(OccurTime).Append("\n");
            sb.Append("  RecoverTime: ").Append(RecoverTime).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  ReporterId: ").Append(ReporterId).Append("\n");
            sb.Append("  RepairerId: ").Append(RepairerId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((FaultRecord)obj);
        }

        /// <summary>
        /// Returns true if FaultRecord instances are equal
        /// </summary>
        /// <param name="other">Instance of FaultRecord to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FaultRecord other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    FaultId == other.FaultId ||
                    
                    FaultId.Equals(other.FaultId)
                ) && 
                (
                    LineId == other.LineId ||
                    
                    LineId.Equals(other.LineId)
                ) && 
                (
                    FaultType == other.FaultType ||
                    FaultType != null &&
                    FaultType.Equals(other.FaultType)
                ) && 
                (
                    Description == other.Description ||
                    Description != null &&
                    Description.Equals(other.Description)
                ) && 
                (
                    OccurTime == other.OccurTime ||
                    
                    OccurTime.Equals(other.OccurTime)
                ) && 
                (
                    RecoverTime == other.RecoverTime ||
                    RecoverTime != null &&
                    RecoverTime.Equals(other.RecoverTime)
                ) && 
                (
                    Status == other.Status ||
                    
                    Status.Equals(other.Status)
                ) && 
                (
                    ReporterId == other.ReporterId ||
                    
                    ReporterId.Equals(other.ReporterId)
                ) && 
                (
                    RepairerId == other.RepairerId ||
                    RepairerId != null &&
                    RepairerId.Equals(other.RepairerId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + FaultId.GetHashCode();
                    
                    hashCode = hashCode * 59 + LineId.GetHashCode();
                    if (FaultType != null)
                    hashCode = hashCode * 59 + FaultType.GetHashCode();
                    if (Description != null)
                    hashCode = hashCode * 59 + Description.GetHashCode();
                    
                    hashCode = hashCode * 59 + OccurTime.GetHashCode();
                    if (RecoverTime != null)
                    hashCode = hashCode * 59 + RecoverTime.GetHashCode();
                    
                    hashCode = hashCode * 59 + Status.GetHashCode();
                    
                    hashCode = hashCode * 59 + ReporterId.GetHashCode();
                    if (RepairerId != null)
                    hashCode = hashCode * 59 + RepairerId.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(FaultRecord left, FaultRecord right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(FaultRecord left, FaultRecord right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
