/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class InventoryAlertEvent : IEquatable<InventoryAlertEvent>
    {
        /// <summary>
        /// Gets or Sets AlertId
        /// </summary>
        [Required]
        [DataMember(Name="alert_id", EmitDefaultValue=true)]
        public long AlertId { get; set; }

        /// <summary>
        /// Gets or Sets MaterialId
        /// </summary>
        [Required]
        [DataMember(Name="material_id", EmitDefaultValue=true)]
        public long MaterialId { get; set; }

        /// <summary>
        /// Gets or Sets MaterialName
        /// </summary>
        [DataMember(Name="material_name", EmitDefaultValue=false)]
        public string MaterialName { get; set; }


        /// <summary>
        /// Gets or Sets AlertType
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<AlertTypeEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum AlertTypeEnum
        {
            
            /// <summary>
            /// Enum LowStockEnum for low_stock
            /// </summary>
            [EnumMember(Value = "low_stock")]
            LowStockEnum = 1
        }

        /// <summary>
        /// Gets or Sets AlertType
        /// </summary>
        [Required]
        [DataMember(Name="alert_type", EmitDefaultValue=true)]
        public AlertTypeEnum AlertType { get; set; }

        /// <summary>
        /// Gets or Sets AvailableQty
        /// </summary>
        [Required]
        [DataMember(Name="available_qty", EmitDefaultValue=true)]
        public decimal AvailableQty { get; set; }

        /// <summary>
        /// Gets or Sets Threshold
        /// </summary>
        [Required]
        [DataMember(Name="threshold", EmitDefaultValue=true)]
        public decimal Threshold { get; set; }

        /// <summary>
        /// Gets or Sets AlertTime
        /// </summary>
        [Required]
        [DataMember(Name="alert_time", EmitDefaultValue=true)]
        public DateTime AlertTime { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [Required]
        [DataMember(Name="status", EmitDefaultValue=true)]
        public InventoryAlertStatus Status { get; set; }

        /// <summary>
        /// Gets or Sets HandlerId
        /// </summary>
        [DataMember(Name="handler_id", EmitDefaultValue=true)]
        public long? HandlerId { get; set; }

        /// <summary>
        /// Gets or Sets HandleTime
        /// </summary>
        [DataMember(Name="handle_time", EmitDefaultValue=true)]
        public DateTime? HandleTime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InventoryAlertEvent {\n");
            sb.Append("  AlertId: ").Append(AlertId).Append("\n");
            sb.Append("  MaterialId: ").Append(MaterialId).Append("\n");
            sb.Append("  MaterialName: ").Append(MaterialName).Append("\n");
            sb.Append("  AlertType: ").Append(AlertType).Append("\n");
            sb.Append("  AvailableQty: ").Append(AvailableQty).Append("\n");
            sb.Append("  Threshold: ").Append(Threshold).Append("\n");
            sb.Append("  AlertTime: ").Append(AlertTime).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  HandlerId: ").Append(HandlerId).Append("\n");
            sb.Append("  HandleTime: ").Append(HandleTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InventoryAlertEvent)obj);
        }

        /// <summary>
        /// Returns true if InventoryAlertEvent instances are equal
        /// </summary>
        /// <param name="other">Instance of InventoryAlertEvent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InventoryAlertEvent other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    AlertId == other.AlertId ||
                    
                    AlertId.Equals(other.AlertId)
                ) && 
                (
                    MaterialId == other.MaterialId ||
                    
                    MaterialId.Equals(other.MaterialId)
                ) && 
                (
                    MaterialName == other.MaterialName ||
                    MaterialName != null &&
                    MaterialName.Equals(other.MaterialName)
                ) && 
                (
                    AlertType == other.AlertType ||
                    
                    AlertType.Equals(other.AlertType)
                ) && 
                (
                    AvailableQty == other.AvailableQty ||
                    
                    AvailableQty.Equals(other.AvailableQty)
                ) && 
                (
                    Threshold == other.Threshold ||
                    
                    Threshold.Equals(other.Threshold)
                ) && 
                (
                    AlertTime == other.AlertTime ||
                    
                    AlertTime.Equals(other.AlertTime)
                ) && 
                (
                    Status == other.Status ||
                    
                    Status.Equals(other.Status)
                ) && 
                (
                    HandlerId == other.HandlerId ||
                    HandlerId != null &&
                    HandlerId.Equals(other.HandlerId)
                ) && 
                (
                    HandleTime == other.HandleTime ||
                    HandleTime != null &&
                    HandleTime.Equals(other.HandleTime)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + AlertId.GetHashCode();
                    
                    hashCode = hashCode * 59 + MaterialId.GetHashCode();
                    if (MaterialName != null)
                    hashCode = hashCode * 59 + MaterialName.GetHashCode();
                    
                    hashCode = hashCode * 59 + AlertType.GetHashCode();
                    
                    hashCode = hashCode * 59 + AvailableQty.GetHashCode();
                    
                    hashCode = hashCode * 59 + Threshold.GetHashCode();
                    
                    hashCode = hashCode * 59 + AlertTime.GetHashCode();
                    
                    hashCode = hashCode * 59 + Status.GetHashCode();
                    if (HandlerId != null)
                    hashCode = hashCode * 59 + HandlerId.GetHashCode();
                    if (HandleTime != null)
                    hashCode = hashCode * 59 + HandleTime.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InventoryAlertEvent left, InventoryAlertEvent right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InventoryAlertEvent left, InventoryAlertEvent right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
