/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class LineTypeSaveRequest : IEquatable<LineTypeSaveRequest>
    {
        /// <summary>
        /// 为空表示新增，非空表示更新。
        /// </summary>
        /// <value>为空表示新增，非空表示更新。</value>
        [DataMember(Name="type_id", EmitDefaultValue=true)]
        public long? TypeId { get; set; }

        /// <summary>
        /// Gets or Sets TypeName
        /// </summary>
        [Required]
        [MinLength(1)]
        [DataMember(Name="type_name", EmitDefaultValue=false)]
        public string TypeName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LineTypeSaveRequest {\n");
            sb.Append("  TypeId: ").Append(TypeId).Append("\n");
            sb.Append("  TypeName: ").Append(TypeName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((LineTypeSaveRequest)obj);
        }

        /// <summary>
        /// Returns true if LineTypeSaveRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of LineTypeSaveRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LineTypeSaveRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    TypeId == other.TypeId ||
                    TypeId != null &&
                    TypeId.Equals(other.TypeId)
                ) && 
                (
                    TypeName == other.TypeName ||
                    TypeName != null &&
                    TypeName.Equals(other.TypeName)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (TypeId != null)
                    hashCode = hashCode * 59 + TypeId.GetHashCode();
                    if (TypeName != null)
                    hashCode = hashCode * 59 + TypeName.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(LineTypeSaveRequest left, LineTypeSaveRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(LineTypeSaveRequest left, LineTypeSaveRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
