/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class LoginLog : IEquatable<LoginLog>
    {
        /// <summary>
        /// Gets or Sets LogId
        /// </summary>
        [DataMember(Name="log_id", EmitDefaultValue=true)]
        public int LogId { get; set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [DataMember(Name="user_id", EmitDefaultValue=true)]
        public int UserId { get; set; }

        /// <summary>
        /// Gets or Sets LoginTime
        /// </summary>
        [DataMember(Name="login_time", EmitDefaultValue=true)]
        public DateTime LoginTime { get; set; }

        /// <summary>
        /// Gets or Sets IpAddress
        /// </summary>
        [DataMember(Name="ip_address", EmitDefaultValue=false)]
        public string IpAddress { get; set; }


        /// <summary>
        /// Gets or Sets Result
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<ResultEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ResultEnum
        {
            
            /// <summary>
            /// Enum SuccessEnum for success
            /// </summary>
            [EnumMember(Value = "success")]
            SuccessEnum = 1,
            
            /// <summary>
            /// Enum FailureEnum for failure
            /// </summary>
            [EnumMember(Value = "failure")]
            FailureEnum = 2
        }

        /// <summary>
        /// Gets or Sets Result
        /// </summary>
        [DataMember(Name="result", EmitDefaultValue=true)]
        public ResultEnum Result { get; set; }

        /// <summary>
        /// Gets or Sets FailReason
        /// </summary>
        [DataMember(Name="fail_reason", EmitDefaultValue=true)]
        public string FailReason { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LoginLog {\n");
            sb.Append("  LogId: ").Append(LogId).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  LoginTime: ").Append(LoginTime).Append("\n");
            sb.Append("  IpAddress: ").Append(IpAddress).Append("\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("  FailReason: ").Append(FailReason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((LoginLog)obj);
        }

        /// <summary>
        /// Returns true if LoginLog instances are equal
        /// </summary>
        /// <param name="other">Instance of LoginLog to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LoginLog other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    LogId == other.LogId ||
                    
                    LogId.Equals(other.LogId)
                ) && 
                (
                    UserId == other.UserId ||
                    
                    UserId.Equals(other.UserId)
                ) && 
                (
                    LoginTime == other.LoginTime ||
                    
                    LoginTime.Equals(other.LoginTime)
                ) && 
                (
                    IpAddress == other.IpAddress ||
                    IpAddress != null &&
                    IpAddress.Equals(other.IpAddress)
                ) && 
                (
                    Result == other.Result ||
                    
                    Result.Equals(other.Result)
                ) && 
                (
                    FailReason == other.FailReason ||
                    FailReason != null &&
                    FailReason.Equals(other.FailReason)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + LogId.GetHashCode();
                    
                    hashCode = hashCode * 59 + UserId.GetHashCode();
                    
                    hashCode = hashCode * 59 + LoginTime.GetHashCode();
                    if (IpAddress != null)
                    hashCode = hashCode * 59 + IpAddress.GetHashCode();
                    
                    hashCode = hashCode * 59 + Result.GetHashCode();
                    if (FailReason != null)
                    hashCode = hashCode * 59 + FailReason.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(LoginLog left, LoginLog right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(LoginLog left, LoginLog right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
