/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class MaterialStock : IEquatable<MaterialStock>
    {
        /// <summary>
        /// Gets or Sets MaterialId
        /// </summary>
        [DataMember(Name="material_id", EmitDefaultValue=true)]
        public int MaterialId { get; set; }

        /// <summary>
        /// Gets or Sets AvailableQty
        /// </summary>
        [DataMember(Name="available_qty", EmitDefaultValue=true)]
        public double AvailableQty { get; set; }

        /// <summary>
        /// Gets or Sets LockedQty
        /// </summary>
        [DataMember(Name="locked_qty", EmitDefaultValue=true)]
        public double LockedQty { get; set; }

        /// <summary>
        /// Gets or Sets LastInDate
        /// </summary>
        [DataMember(Name="last_in_date", EmitDefaultValue=true)]
        public DateTime? LastInDate { get; set; }

        /// <summary>
        /// Gets or Sets LastOutDate
        /// </summary>
        [DataMember(Name="last_out_date", EmitDefaultValue=true)]
        public DateTime? LastOutDate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MaterialStock {\n");
            sb.Append("  MaterialId: ").Append(MaterialId).Append("\n");
            sb.Append("  AvailableQty: ").Append(AvailableQty).Append("\n");
            sb.Append("  LockedQty: ").Append(LockedQty).Append("\n");
            sb.Append("  LastInDate: ").Append(LastInDate).Append("\n");
            sb.Append("  LastOutDate: ").Append(LastOutDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((MaterialStock)obj);
        }

        /// <summary>
        /// Returns true if MaterialStock instances are equal
        /// </summary>
        /// <param name="other">Instance of MaterialStock to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MaterialStock other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    MaterialId == other.MaterialId ||
                    
                    MaterialId.Equals(other.MaterialId)
                ) && 
                (
                    AvailableQty == other.AvailableQty ||
                    
                    AvailableQty.Equals(other.AvailableQty)
                ) && 
                (
                    LockedQty == other.LockedQty ||
                    
                    LockedQty.Equals(other.LockedQty)
                ) && 
                (
                    LastInDate == other.LastInDate ||
                    LastInDate != null &&
                    LastInDate.Equals(other.LastInDate)
                ) && 
                (
                    LastOutDate == other.LastOutDate ||
                    LastOutDate != null &&
                    LastOutDate.Equals(other.LastOutDate)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + MaterialId.GetHashCode();
                    
                    hashCode = hashCode * 59 + AvailableQty.GetHashCode();
                    
                    hashCode = hashCode * 59 + LockedQty.GetHashCode();
                    if (LastInDate != null)
                    hashCode = hashCode * 59 + LastInDate.GetHashCode();
                    if (LastOutDate != null)
                    hashCode = hashCode * 59 + LastOutDate.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(MaterialStock left, MaterialStock right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(MaterialStock left, MaterialStock right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
