/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class MaterialShortageItem : IEquatable<MaterialShortageItem>
    {
        /// <summary>
        /// Gets or Sets MaterialId
        /// </summary>
        /* <example>1001</example> */
        [Required]
        [DataMember(Name="material_id", EmitDefaultValue=true)]
        public long MaterialId { get; set; }

        /// <summary>
        /// Gets or Sets MaterialName
        /// </summary>
        /* <example>钢板</example> */
        [DataMember(Name="material_name", EmitDefaultValue=false)]
        public string MaterialName { get; set; }

        /// <summary>
        /// Gets or Sets ParentMaterialId
        /// </summary>
        [DataMember(Name="parent_material_id", EmitDefaultValue=true)]
        public long? ParentMaterialId { get; set; }

        /// <summary>
        /// Gets or Sets Level
        /// </summary>
        /* <example>2</example> */
        [Required]
        [DataMember(Name="level", EmitDefaultValue=true)]
        public int Level { get; set; }

        /// <summary>
        /// 毛需求数量，由后端根据请求中的生产产品、生产数量和 BOM 版本递归展开 bom.quantity， 并按 bom.loss_rate 做损耗补偿后汇总得到。单位与物料 material.unit 一致， 保留两位小数，取值范围大于等于 0；当 BOM 明细不存在时按 0 处理。 
        /// </summary>
        /// <value>毛需求数量，由后端根据请求中的生产产品、生产数量和 BOM 版本递归展开 bom.quantity， 并按 bom.loss_rate 做损耗补偿后汇总得到。单位与物料 material.unit 一致， 保留两位小数，取值范围大于等于 0；当 BOM 明细不存在时按 0 处理。 </value>
        [Required]
        [DataMember(Name="gross_requirement", EmitDefaultValue=true)]
        public decimal GrossRequirement { get; set; }

        /// <summary>
        /// 库存可用数量，来源于 material_stock.available_qty，单位与物料 material.unit 一致，取值范围大于等于 0。
        /// </summary>
        /// <value>库存可用数量，来源于 material_stock.available_qty，单位与物料 material.unit 一致，取值范围大于等于 0。</value>
        [Required]
        [DataMember(Name="available_qty", EmitDefaultValue=true)]
        public decimal AvailableQty { get; set; }

        /// <summary>
        /// 在途数量，由后端汇总 purchase_order_item 中同一 material_id 且采购订单状态为 submitted 或 partial_received 的未到货数量 sum(quantity - received_qty) 得到。单位与物料 material.unit 一致，取值范围大于等于 0；没有匹配采购明细时返回 0。 
        /// </summary>
        /// <value>在途数量，由后端汇总 purchase_order_item 中同一 material_id 且采购订单状态为 submitted 或 partial_received 的未到货数量 sum(quantity - received_qty) 得到。单位与物料 material.unit 一致，取值范围大于等于 0；没有匹配采购明细时返回 0。 </value>
        [Required]
        [DataMember(Name="in_transit_qty", EmitDefaultValue=true)]
        public decimal InTransitQty { get; set; }

        /// <summary>
        /// 安全库存数量，来源于 material.safety_stock，单位与物料 material.unit 一致，取值范围大于等于 0；为空时按 0 处理。
        /// </summary>
        /// <value>安全库存数量，来源于 material.safety_stock，单位与物料 material.unit 一致，取值范围大于等于 0；为空时按 0 处理。</value>
        [Required]
        [DataMember(Name="safety_stock", EmitDefaultValue=true)]
        public decimal SafetyStock { get; set; }

        /// <summary>
        /// 净缺料数量，由后端根据 gross_requirement、material_stock.available_qty、 在途数量和 material.safety_stock 统一计算，公式为 max(gross_requirement - available_qty - in_transit_qty + safety_stock, 0)。 单位与物料 material.unit 一致，保留两位小数，取值范围大于等于 0。 
        /// </summary>
        /// <value>净缺料数量，由后端根据 gross_requirement、material_stock.available_qty、 在途数量和 material.safety_stock 统一计算，公式为 max(gross_requirement - available_qty - in_transit_qty + safety_stock, 0)。 单位与物料 material.unit 一致，保留两位小数，取值范围大于等于 0。 </value>
        [Required]
        [DataMember(Name="net_shortage_qty", EmitDefaultValue=true)]
        public decimal NetShortageQty { get; set; }

        /// <summary>
        /// 建议采购数量，由后端基于 net_shortage_qty 得到，当前口径为 suggested_purchase_qty &#x3D; net_shortage_qty。 单位与物料 material.unit 一致，保留两位小数，取值范围大于等于 0；后续如引入最小采购批量或包装规格， 应在后端统一调整该字段计算逻辑。 
        /// </summary>
        /// <value>建议采购数量，由后端基于 net_shortage_qty 得到，当前口径为 suggested_purchase_qty &#x3D; net_shortage_qty。 单位与物料 material.unit 一致，保留两位小数，取值范围大于等于 0；后续如引入最小采购批量或包装规格， 应在后端统一调整该字段计算逻辑。 </value>
        [DataMember(Name="suggested_purchase_qty", EmitDefaultValue=true)]
        public decimal SuggestedPurchaseQty { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MaterialShortageItem {\n");
            sb.Append("  MaterialId: ").Append(MaterialId).Append("\n");
            sb.Append("  MaterialName: ").Append(MaterialName).Append("\n");
            sb.Append("  ParentMaterialId: ").Append(ParentMaterialId).Append("\n");
            sb.Append("  Level: ").Append(Level).Append("\n");
            sb.Append("  GrossRequirement: ").Append(GrossRequirement).Append("\n");
            sb.Append("  AvailableQty: ").Append(AvailableQty).Append("\n");
            sb.Append("  InTransitQty: ").Append(InTransitQty).Append("\n");
            sb.Append("  SafetyStock: ").Append(SafetyStock).Append("\n");
            sb.Append("  NetShortageQty: ").Append(NetShortageQty).Append("\n");
            sb.Append("  SuggestedPurchaseQty: ").Append(SuggestedPurchaseQty).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((MaterialShortageItem)obj);
        }

        /// <summary>
        /// Returns true if MaterialShortageItem instances are equal
        /// </summary>
        /// <param name="other">Instance of MaterialShortageItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MaterialShortageItem other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    MaterialId == other.MaterialId ||
                    
                    MaterialId.Equals(other.MaterialId)
                ) && 
                (
                    MaterialName == other.MaterialName ||
                    MaterialName != null &&
                    MaterialName.Equals(other.MaterialName)
                ) && 
                (
                    ParentMaterialId == other.ParentMaterialId ||
                    ParentMaterialId != null &&
                    ParentMaterialId.Equals(other.ParentMaterialId)
                ) && 
                (
                    Level == other.Level ||
                    
                    Level.Equals(other.Level)
                ) && 
                (
                    GrossRequirement == other.GrossRequirement ||
                    
                    GrossRequirement.Equals(other.GrossRequirement)
                ) && 
                (
                    AvailableQty == other.AvailableQty ||
                    
                    AvailableQty.Equals(other.AvailableQty)
                ) && 
                (
                    InTransitQty == other.InTransitQty ||
                    
                    InTransitQty.Equals(other.InTransitQty)
                ) && 
                (
                    SafetyStock == other.SafetyStock ||
                    
                    SafetyStock.Equals(other.SafetyStock)
                ) && 
                (
                    NetShortageQty == other.NetShortageQty ||
                    
                    NetShortageQty.Equals(other.NetShortageQty)
                ) && 
                (
                    SuggestedPurchaseQty == other.SuggestedPurchaseQty ||
                    
                    SuggestedPurchaseQty.Equals(other.SuggestedPurchaseQty)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + MaterialId.GetHashCode();
                    if (MaterialName != null)
                    hashCode = hashCode * 59 + MaterialName.GetHashCode();
                    if (ParentMaterialId != null)
                    hashCode = hashCode * 59 + ParentMaterialId.GetHashCode();
                    
                    hashCode = hashCode * 59 + Level.GetHashCode();
                    
                    hashCode = hashCode * 59 + GrossRequirement.GetHashCode();
                    
                    hashCode = hashCode * 59 + AvailableQty.GetHashCode();
                    
                    hashCode = hashCode * 59 + InTransitQty.GetHashCode();
                    
                    hashCode = hashCode * 59 + SafetyStock.GetHashCode();
                    
                    hashCode = hashCode * 59 + NetShortageQty.GetHashCode();
                    
                    hashCode = hashCode * 59 + SuggestedPurchaseQty.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(MaterialShortageItem left, MaterialShortageItem right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(MaterialShortageItem left, MaterialShortageItem right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
