/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
        /// <summary>
        /// 库存状态。zero 表示可用库存小于等于 0；low 表示可用库存低于安全库存；locked 表示存在锁定库存；normal 表示库存正常。按 zero、low、locked、normal 的优先级判定。
        /// </summary>
        /// <value>库存状态。zero 表示可用库存小于等于 0；low 表示可用库存低于安全库存；locked 表示存在锁定库存；normal 表示库存正常。按 zero、low、locked、normal 的优先级判定。</value>
        [TypeConverter(typeof(CustomEnumConverter<MaterialStockStatus>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum MaterialStockStatus
        {
            
            /// <summary>
            /// Enum NormalEnum for normal
            /// </summary>
            [EnumMember(Value = "normal")]
            NormalEnum = 1,
            
            /// <summary>
            /// Enum LowEnum for low
            /// </summary>
            [EnumMember(Value = "low")]
            LowEnum = 2,
            
            /// <summary>
            /// Enum ZeroEnum for zero
            /// </summary>
            [EnumMember(Value = "zero")]
            ZeroEnum = 3,
            
            /// <summary>
            /// Enum LockedEnum for locked
            /// </summary>
            [EnumMember(Value = "locked")]
            LockedEnum = 4
        }
}
