/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ObsoleteMaterialDetectRequest : IEquatable<ObsoleteMaterialDetectRequest>
    {
        /// <summary>
        /// Gets or Sets IdleDaysThreshold
        /// </summary>
        [Required]
        [DataMember(Name="idle_days_threshold", EmitDefaultValue=true)]
        public int IdleDaysThreshold { get; set; }

        /// <summary>
        /// Gets or Sets MaterialId
        /// </summary>
        [DataMember(Name="material_id", EmitDefaultValue=true)]
        public long? MaterialId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ObsoleteMaterialDetectRequest {\n");
            sb.Append("  IdleDaysThreshold: ").Append(IdleDaysThreshold).Append("\n");
            sb.Append("  MaterialId: ").Append(MaterialId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ObsoleteMaterialDetectRequest)obj);
        }

        /// <summary>
        /// Returns true if ObsoleteMaterialDetectRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of ObsoleteMaterialDetectRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ObsoleteMaterialDetectRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    IdleDaysThreshold == other.IdleDaysThreshold ||
                    
                    IdleDaysThreshold.Equals(other.IdleDaysThreshold)
                ) && 
                (
                    MaterialId == other.MaterialId ||
                    MaterialId != null &&
                    MaterialId.Equals(other.MaterialId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + IdleDaysThreshold.GetHashCode();
                    if (MaterialId != null)
                    hashCode = hashCode * 59 + MaterialId.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ObsoleteMaterialDetectRequest left, ObsoleteMaterialDetectRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ObsoleteMaterialDetectRequest left, ObsoleteMaterialDetectRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
