/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
        /// <summary>
        /// 稳定的系统权限标识。角色名称和显示文案可以变化，权限码只能通过版本化 API 契约与数据库迁移调整。
        /// </summary>
        /// <value>稳定的系统权限标识。角色名称和显示文案可以变化，权限码只能通过版本化 API 契约与数据库迁移调整。</value>
        [TypeConverter(typeof(CustomEnumConverter<PermissionCode>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum PermissionCode
        {
            
            /// <summary>
            /// Enum SystemUserViewEnum for system:user:view
            /// </summary>
            [EnumMember(Value = "system:user:view")]
            SystemUserViewEnum = 1,
            
            /// <summary>
            /// Enum SystemUserCreateEnum for system:user:create
            /// </summary>
            [EnumMember(Value = "system:user:create")]
            SystemUserCreateEnum = 2,
            
            /// <summary>
            /// Enum SystemUserUpdateEnum for system:user:update
            /// </summary>
            [EnumMember(Value = "system:user:update")]
            SystemUserUpdateEnum = 3,
            
            /// <summary>
            /// Enum SystemUserDeleteEnum for system:user:delete
            /// </summary>
            [EnumMember(Value = "system:user:delete")]
            SystemUserDeleteEnum = 4,
            
            /// <summary>
            /// Enum SystemUserAssignRoleEnum for system:user:assign-role
            /// </summary>
            [EnumMember(Value = "system:user:assign-role")]
            SystemUserAssignRoleEnum = 5,
            
            /// <summary>
            /// Enum SystemRoleViewEnum for system:role:view
            /// </summary>
            [EnumMember(Value = "system:role:view")]
            SystemRoleViewEnum = 6,
            
            /// <summary>
            /// Enum SystemRoleCreateEnum for system:role:create
            /// </summary>
            [EnumMember(Value = "system:role:create")]
            SystemRoleCreateEnum = 7,
            
            /// <summary>
            /// Enum SystemRoleUpdateEnum for system:role:update
            /// </summary>
            [EnumMember(Value = "system:role:update")]
            SystemRoleUpdateEnum = 8,
            
            /// <summary>
            /// Enum SystemRoleDeleteEnum for system:role:delete
            /// </summary>
            [EnumMember(Value = "system:role:delete")]
            SystemRoleDeleteEnum = 9,
            
            /// <summary>
            /// Enum SystemRoleAssignPermissionEnum for system:role:assign-permission
            /// </summary>
            [EnumMember(Value = "system:role:assign-permission")]
            SystemRoleAssignPermissionEnum = 10,
            
            /// <summary>
            /// Enum SystemPermissionViewEnum for system:permission:view
            /// </summary>
            [EnumMember(Value = "system:permission:view")]
            SystemPermissionViewEnum = 11,
            
            /// <summary>
            /// Enum SystemAuditLoginViewEnum for system:audit:login:view
            /// </summary>
            [EnumMember(Value = "system:audit:login:view")]
            SystemAuditLoginViewEnum = 12,
            
            /// <summary>
            /// Enum SystemAuditOperationViewEnum for system:audit:operation:view
            /// </summary>
            [EnumMember(Value = "system:audit:operation:view")]
            SystemAuditOperationViewEnum = 13,
            
            /// <summary>
            /// Enum SystemAuditOperationCreateEnum for system:audit:operation:create
            /// </summary>
            [EnumMember(Value = "system:audit:operation:create")]
            SystemAuditOperationCreateEnum = 14,
            
            /// <summary>
            /// Enum MaterialItemViewEnum for material:item:view
            /// </summary>
            [EnumMember(Value = "material:item:view")]
            MaterialItemViewEnum = 15,
            
            /// <summary>
            /// Enum MaterialItemCreateEnum for material:item:create
            /// </summary>
            [EnumMember(Value = "material:item:create")]
            MaterialItemCreateEnum = 16,
            
            /// <summary>
            /// Enum MaterialItemUpdateEnum for material:item:update
            /// </summary>
            [EnumMember(Value = "material:item:update")]
            MaterialItemUpdateEnum = 17,
            
            /// <summary>
            /// Enum MaterialItemDeleteEnum for material:item:delete
            /// </summary>
            [EnumMember(Value = "material:item:delete")]
            MaterialItemDeleteEnum = 18,
            
            /// <summary>
            /// Enum MaterialCategoryViewEnum for material:category:view
            /// </summary>
            [EnumMember(Value = "material:category:view")]
            MaterialCategoryViewEnum = 19,
            
            /// <summary>
            /// Enum MaterialCategoryCreateEnum for material:category:create
            /// </summary>
            [EnumMember(Value = "material:category:create")]
            MaterialCategoryCreateEnum = 20,
            
            /// <summary>
            /// Enum MaterialCategoryUpdateEnum for material:category:update
            /// </summary>
            [EnumMember(Value = "material:category:update")]
            MaterialCategoryUpdateEnum = 21,
            
            /// <summary>
            /// Enum MaterialCategoryDeleteEnum for material:category:delete
            /// </summary>
            [EnumMember(Value = "material:category:delete")]
            MaterialCategoryDeleteEnum = 22,
            
            /// <summary>
            /// Enum MaterialBomVersionViewEnum for material:bom-version:view
            /// </summary>
            [EnumMember(Value = "material:bom-version:view")]
            MaterialBomVersionViewEnum = 23,
            
            /// <summary>
            /// Enum MaterialBomVersionCreateEnum for material:bom-version:create
            /// </summary>
            [EnumMember(Value = "material:bom-version:create")]
            MaterialBomVersionCreateEnum = 24,
            
            /// <summary>
            /// Enum MaterialBomVersionUpdateEnum for material:bom-version:update
            /// </summary>
            [EnumMember(Value = "material:bom-version:update")]
            MaterialBomVersionUpdateEnum = 25,
            
            /// <summary>
            /// Enum MaterialBomVersionDeleteEnum for material:bom-version:delete
            /// </summary>
            [EnumMember(Value = "material:bom-version:delete")]
            MaterialBomVersionDeleteEnum = 26,
            
            /// <summary>
            /// Enum MaterialBomViewEnum for material:bom:view
            /// </summary>
            [EnumMember(Value = "material:bom:view")]
            MaterialBomViewEnum = 27,
            
            /// <summary>
            /// Enum MaterialBomCreateEnum for material:bom:create
            /// </summary>
            [EnumMember(Value = "material:bom:create")]
            MaterialBomCreateEnum = 28,
            
            /// <summary>
            /// Enum MaterialBomUpdateEnum for material:bom:update
            /// </summary>
            [EnumMember(Value = "material:bom:update")]
            MaterialBomUpdateEnum = 29,
            
            /// <summary>
            /// Enum MaterialBomDeleteEnum for material:bom:delete
            /// </summary>
            [EnumMember(Value = "material:bom:delete")]
            MaterialBomDeleteEnum = 30,
            
            /// <summary>
            /// Enum MaterialBomCheckCycleEnum for material:bom:check-cycle
            /// </summary>
            [EnumMember(Value = "material:bom:check-cycle")]
            MaterialBomCheckCycleEnum = 31,
            
            /// <summary>
            /// Enum MaterialBomTreeViewEnum for material:bom:tree:view
            /// </summary>
            [EnumMember(Value = "material:bom:tree:view")]
            MaterialBomTreeViewEnum = 32,
            
            /// <summary>
            /// Enum MaterialBomReverseViewEnum for material:bom:reverse:view
            /// </summary>
            [EnumMember(Value = "material:bom:reverse:view")]
            MaterialBomReverseViewEnum = 33,
            
            /// <summary>
            /// Enum MaterialCostCalculateEnum for material:cost:calculate
            /// </summary>
            [EnumMember(Value = "material:cost:calculate")]
            MaterialCostCalculateEnum = 34,
            
            /// <summary>
            /// Enum MaterialLossCalculateEnum for material:loss:calculate
            /// </summary>
            [EnumMember(Value = "material:loss:calculate")]
            MaterialLossCalculateEnum = 35,
            
            /// <summary>
            /// Enum InventoryStockViewEnum for inventory:stock:view
            /// </summary>
            [EnumMember(Value = "inventory:stock:view")]
            InventoryStockViewEnum = 36,
            
            /// <summary>
            /// Enum InventoryShortageCalculateEnum for inventory:shortage:calculate
            /// </summary>
            [EnumMember(Value = "inventory:shortage:calculate")]
            InventoryShortageCalculateEnum = 37,
            
            /// <summary>
            /// Enum InventoryAlertViewEnum for inventory:alert:view
            /// </summary>
            [EnumMember(Value = "inventory:alert:view")]
            InventoryAlertViewEnum = 38,
            
            /// <summary>
            /// Enum InventoryAlertGenerateEnum for inventory:alert:generate
            /// </summary>
            [EnumMember(Value = "inventory:alert:generate")]
            InventoryAlertGenerateEnum = 39,
            
            /// <summary>
            /// Enum InventoryAlertHandleEnum for inventory:alert:handle
            /// </summary>
            [EnumMember(Value = "inventory:alert:handle")]
            InventoryAlertHandleEnum = 40,
            
            /// <summary>
            /// Enum InventoryLockViewEnum for inventory:lock:view
            /// </summary>
            [EnumMember(Value = "inventory:lock:view")]
            InventoryLockViewEnum = 41,
            
            /// <summary>
            /// Enum InventoryLockCreateEnum for inventory:lock:create
            /// </summary>
            [EnumMember(Value = "inventory:lock:create")]
            InventoryLockCreateEnum = 42,
            
            /// <summary>
            /// Enum InventoryLockReleaseEnum for inventory:lock:release
            /// </summary>
            [EnumMember(Value = "inventory:lock:release")]
            InventoryLockReleaseEnum = 43,
            
            /// <summary>
            /// Enum InventoryObsoleteViewEnum for inventory:obsolete:view
            /// </summary>
            [EnumMember(Value = "inventory:obsolete:view")]
            InventoryObsoleteViewEnum = 44,
            
            /// <summary>
            /// Enum InventoryObsoleteDetectEnum for inventory:obsolete:detect
            /// </summary>
            [EnumMember(Value = "inventory:obsolete:detect")]
            InventoryObsoleteDetectEnum = 45,
            
            /// <summary>
            /// Enum InventoryObsoleteHandleEnum for inventory:obsolete:handle
            /// </summary>
            [EnumMember(Value = "inventory:obsolete:handle")]
            InventoryObsoleteHandleEnum = 46,
            
            /// <summary>
            /// Enum InventoryCompletionViewEnum for inventory:completion:view
            /// </summary>
            [EnumMember(Value = "inventory:completion:view")]
            InventoryCompletionViewEnum = 47,
            
            /// <summary>
            /// Enum InventoryCompletionCreateEnum for inventory:completion:create
            /// </summary>
            [EnumMember(Value = "inventory:completion:create")]
            InventoryCompletionCreateEnum = 48,
            
            /// <summary>
            /// Enum PurchaseSupplierViewEnum for purchase:supplier:view
            /// </summary>
            [EnumMember(Value = "purchase:supplier:view")]
            PurchaseSupplierViewEnum = 49,
            
            /// <summary>
            /// Enum PurchaseBuyerViewEnum for purchase:buyer:view
            /// </summary>
            [EnumMember(Value = "purchase:buyer:view")]
            PurchaseBuyerViewEnum = 50,
            
            /// <summary>
            /// Enum PurchaseBuyerEligibleEnum for purchase:buyer:eligible
            /// </summary>
            [EnumMember(Value = "purchase:buyer:eligible")]
            PurchaseBuyerEligibleEnum = 51,
            
            /// <summary>
            /// Enum PurchaseOrderViewEnum for purchase:order:view
            /// </summary>
            [EnumMember(Value = "purchase:order:view")]
            PurchaseOrderViewEnum = 52,
            
            /// <summary>
            /// Enum PurchaseOrderCreateEnum for purchase:order:create
            /// </summary>
            [EnumMember(Value = "purchase:order:create")]
            PurchaseOrderCreateEnum = 53,
            
            /// <summary>
            /// Enum PurchaseOrderSubmitEnum for purchase:order:submit
            /// </summary>
            [EnumMember(Value = "purchase:order:submit")]
            PurchaseOrderSubmitEnum = 54,
            
            /// <summary>
            /// Enum PurchaseOrderCancelEnum for purchase:order:cancel
            /// </summary>
            [EnumMember(Value = "purchase:order:cancel")]
            PurchaseOrderCancelEnum = 55,
            
            /// <summary>
            /// Enum PurchaseReceiptViewEnum for purchase:receipt:view
            /// </summary>
            [EnumMember(Value = "purchase:receipt:view")]
            PurchaseReceiptViewEnum = 56,
            
            /// <summary>
            /// Enum PurchaseReceiptCreateEnum for purchase:receipt:create
            /// </summary>
            [EnumMember(Value = "purchase:receipt:create")]
            PurchaseReceiptCreateEnum = 57,
            
            /// <summary>
            /// Enum PurchaseOverdueViewEnum for purchase:overdue:view
            /// </summary>
            [EnumMember(Value = "purchase:overdue:view")]
            PurchaseOverdueViewEnum = 58,
            
            /// <summary>
            /// Enum PurchaseOverdueGenerateEnum for purchase:overdue:generate
            /// </summary>
            [EnumMember(Value = "purchase:overdue:generate")]
            PurchaseOverdueGenerateEnum = 59,
            
            /// <summary>
            /// Enum PurchaseOverdueHandleEnum for purchase:overdue:handle
            /// </summary>
            [EnumMember(Value = "purchase:overdue:handle")]
            PurchaseOverdueHandleEnum = 60,
            
            /// <summary>
            /// Enum ProductionOrderViewEnum for production:order:view
            /// </summary>
            [EnumMember(Value = "production:order:view")]
            ProductionOrderViewEnum = 61,
            
            /// <summary>
            /// Enum ProductionOrderCreateEnum for production:order:create
            /// </summary>
            [EnumMember(Value = "production:order:create")]
            ProductionOrderCreateEnum = 62,
            
            /// <summary>
            /// Enum ProductionOrderUpdateEnum for production:order:update
            /// </summary>
            [EnumMember(Value = "production:order:update")]
            ProductionOrderUpdateEnum = 63,
            
            /// <summary>
            /// Enum ProductionOrderApproveEnum for production:order:approve
            /// </summary>
            [EnumMember(Value = "production:order:approve")]
            ProductionOrderApproveEnum = 64,
            
            /// <summary>
            /// Enum ProductionOrderStartEnum for production:order:start
            /// </summary>
            [EnumMember(Value = "production:order:start")]
            ProductionOrderStartEnum = 65,
            
            /// <summary>
            /// Enum ProductionOrderFinishEnum for production:order:finish
            /// </summary>
            [EnumMember(Value = "production:order:finish")]
            ProductionOrderFinishEnum = 66,
            
            /// <summary>
            /// Enum ProductionOrderCancelEnum for production:order:cancel
            /// </summary>
            [EnumMember(Value = "production:order:cancel")]
            ProductionOrderCancelEnum = 67,
            
            /// <summary>
            /// Enum ProductionLineViewEnum for production:line:view
            /// </summary>
            [EnumMember(Value = "production:line:view")]
            ProductionLineViewEnum = 68,
            
            /// <summary>
            /// Enum ProductionLineCreateEnum for production:line:create
            /// </summary>
            [EnumMember(Value = "production:line:create")]
            ProductionLineCreateEnum = 69,
            
            /// <summary>
            /// Enum ProductionLineUpdateEnum for production:line:update
            /// </summary>
            [EnumMember(Value = "production:line:update")]
            ProductionLineUpdateEnum = 70,
            
            /// <summary>
            /// Enum ProductionLineTypeViewEnum for production:line-type:view
            /// </summary>
            [EnumMember(Value = "production:line-type:view")]
            ProductionLineTypeViewEnum = 71,
            
            /// <summary>
            /// Enum ProductionLineTypeUpdateEnum for production:line-type:update
            /// </summary>
            [EnumMember(Value = "production:line-type:update")]
            ProductionLineTypeUpdateEnum = 72,
            
            /// <summary>
            /// Enum ProductionCapacityConfigViewEnum for production:capacity-config:view
            /// </summary>
            [EnumMember(Value = "production:capacity-config:view")]
            ProductionCapacityConfigViewEnum = 73,
            
            /// <summary>
            /// Enum ProductionCapacityConfigUpdateEnum for production:capacity-config:update
            /// </summary>
            [EnumMember(Value = "production:capacity-config:update")]
            ProductionCapacityConfigUpdateEnum = 74,
            
            /// <summary>
            /// Enum ProductionCalendarViewEnum for production:calendar:view
            /// </summary>
            [EnumMember(Value = "production:calendar:view")]
            ProductionCalendarViewEnum = 75,
            
            /// <summary>
            /// Enum ProductionCalendarUpdateEnum for production:calendar:update
            /// </summary>
            [EnumMember(Value = "production:calendar:update")]
            ProductionCalendarUpdateEnum = 76,
            
            /// <summary>
            /// Enum ProductionCalendarDeleteEnum for production:calendar:delete
            /// </summary>
            [EnumMember(Value = "production:calendar:delete")]
            ProductionCalendarDeleteEnum = 77,
            
            /// <summary>
            /// Enum ProductionCapacityEstimateEnum for production:capacity:estimate
            /// </summary>
            [EnumMember(Value = "production:capacity:estimate")]
            ProductionCapacityEstimateEnum = 78,
            
            /// <summary>
            /// Enum ProductionCapacityDetectEnum for production:capacity:detect
            /// </summary>
            [EnumMember(Value = "production:capacity:detect")]
            ProductionCapacityDetectEnum = 79,
            
            /// <summary>
            /// Enum ProductionCapacityBalanceEnum for production:capacity:balance
            /// </summary>
            [EnumMember(Value = "production:capacity:balance")]
            ProductionCapacityBalanceEnum = 80,
            
            /// <summary>
            /// Enum ProductionFaultViewEnum for production:fault:view
            /// </summary>
            [EnumMember(Value = "production:fault:view")]
            ProductionFaultViewEnum = 81,
            
            /// <summary>
            /// Enum ProductionFaultReportEnum for production:fault:report
            /// </summary>
            [EnumMember(Value = "production:fault:report")]
            ProductionFaultReportEnum = 82,
            
            /// <summary>
            /// Enum ProductionFaultClaimEnum for production:fault:claim
            /// </summary>
            [EnumMember(Value = "production:fault:claim")]
            ProductionFaultClaimEnum = 83,
            
            /// <summary>
            /// Enum ProductionFaultUpdateAssignedEnum for production:fault:update-assigned
            /// </summary>
            [EnumMember(Value = "production:fault:update-assigned")]
            ProductionFaultUpdateAssignedEnum = 84,
            
            /// <summary>
            /// Enum ProductionFaultUpdateAnyEnum for production:fault:update-any
            /// </summary>
            [EnumMember(Value = "production:fault:update-any")]
            ProductionFaultUpdateAnyEnum = 85,
            
            /// <summary>
            /// Enum ProductionLineStatusUpdateEnum for production:line-status:update
            /// </summary>
            [EnumMember(Value = "production:line-status:update")]
            ProductionLineStatusUpdateEnum = 86,
            
            /// <summary>
            /// Enum ExternalOrderViewOwnEnum for external-order:view-own
            /// </summary>
            [EnumMember(Value = "external-order:view-own")]
            ExternalOrderViewOwnEnum = 87,
            
            /// <summary>
            /// Enum ExternalOrderViewAllEnum for external-order:view-all
            /// </summary>
            [EnumMember(Value = "external-order:view-all")]
            ExternalOrderViewAllEnum = 88,
            
            /// <summary>
            /// Enum ExternalOrderCreateOwnEnum for external-order:create-own
            /// </summary>
            [EnumMember(Value = "external-order:create-own")]
            ExternalOrderCreateOwnEnum = 89,
            
            /// <summary>
            /// Enum ExternalOrderCreateForCustomerEnum for external-order:create-for-customer
            /// </summary>
            [EnumMember(Value = "external-order:create-for-customer")]
            ExternalOrderCreateForCustomerEnum = 90,
            
            /// <summary>
            /// Enum ExternalOrderReviewEnum for external-order:review
            /// </summary>
            [EnumMember(Value = "external-order:review")]
            ExternalOrderReviewEnum = 91,
            
            /// <summary>
            /// Enum ExternalOrderConvertEnum for external-order:convert
            /// </summary>
            [EnumMember(Value = "external-order:convert")]
            ExternalOrderConvertEnum = 92,
            
            /// <summary>
            /// Enum TraceConsumptionViewEnum for trace:consumption:view
            /// </summary>
            [EnumMember(Value = "trace:consumption:view")]
            TraceConsumptionViewEnum = 93,
            
            /// <summary>
            /// Enum TraceConsumptionCreateEnum for trace:consumption:create
            /// </summary>
            [EnumMember(Value = "trace:consumption:create")]
            TraceConsumptionCreateEnum = 94,
            
            /// <summary>
            /// Enum TraceConsumptionUpdateEnum for trace:consumption:update
            /// </summary>
            [EnumMember(Value = "trace:consumption:update")]
            TraceConsumptionUpdateEnum = 95,
            
            /// <summary>
            /// Enum TraceConsumptionDeleteEnum for trace:consumption:delete
            /// </summary>
            [EnumMember(Value = "trace:consumption:delete")]
            TraceConsumptionDeleteEnum = 96,
            
            /// <summary>
            /// Enum TraceProductViewEnum for trace:product:view
            /// </summary>
            [EnumMember(Value = "trace:product:view")]
            TraceProductViewEnum = 97,
            
            /// <summary>
            /// Enum TraceMaterialViewEnum for trace:material:view
            /// </summary>
            [EnumMember(Value = "trace:material:view")]
            TraceMaterialViewEnum = 98,
            
            /// <summary>
            /// Enum TraceImpactAnalyzeEnum for trace:impact:analyze
            /// </summary>
            [EnumMember(Value = "trace:impact:analyze")]
            TraceImpactAnalyzeEnum = 99
        }
}
