/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Permission : IEquatable<Permission>
    {
        /// <summary>
        /// Gets or Sets PermissionId
        /// </summary>
        [Required]
        [DataMember(Name="permission_id", EmitDefaultValue=true)]
        public int PermissionId { get; set; }

        /// <summary>
        /// Gets or Sets PermissionCode
        /// </summary>
        [Required]
        [DataMember(Name="permission_code", EmitDefaultValue=true)]
        public PermissionCode PermissionCode { get; set; }

        /// <summary>
        /// 权限在管理界面中的模块分组名称。
        /// </summary>
        /// <value>权限在管理界面中的模块分组名称。</value>
        [Required]
        [DataMember(Name="module_name", EmitDefaultValue=false)]
        public string ModuleName { get; set; }

        /// <summary>
        /// 权限对应资源的显示名称。
        /// </summary>
        /// <value>权限对应资源的显示名称。</value>
        [Required]
        [DataMember(Name="resource_name", EmitDefaultValue=false)]
        public string ResourceName { get; set; }

        /// <summary>
        /// 权限对应操作的显示名称。
        /// </summary>
        /// <value>权限对应操作的显示名称。</value>
        [Required]
        [DataMember(Name="action_name", EmitDefaultValue=false)]
        public string ActionName { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="description", EmitDefaultValue=true)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets SortOrder
        /// </summary>
        [Required]
        [DataMember(Name="sort_order", EmitDefaultValue=true)]
        public int SortOrder { get; set; }


        /// <summary>
        /// valid 权限参与授权和角色配置；disabled 权限不再产生有效授权。
        /// </summary>
        /// <value>valid 权限参与授权和角色配置；disabled 权限不再产生有效授权。</value>
        [TypeConverter(typeof(CustomEnumConverter<StatusEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum StatusEnum
        {
            
            /// <summary>
            /// Enum ValidEnum for valid
            /// </summary>
            [EnumMember(Value = "valid")]
            ValidEnum = 1,
            
            /// <summary>
            /// Enum DisabledEnum for disabled
            /// </summary>
            [EnumMember(Value = "disabled")]
            DisabledEnum = 2
        }

        /// <summary>
        /// valid 权限参与授权和角色配置；disabled 权限不再产生有效授权。
        /// </summary>
        /// <value>valid 权限参与授权和角色配置；disabled 权限不再产生有效授权。</value>
        [Required]
        [DataMember(Name="status", EmitDefaultValue=true)]
        public StatusEnum Status { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Permission {\n");
            sb.Append("  PermissionId: ").Append(PermissionId).Append("\n");
            sb.Append("  PermissionCode: ").Append(PermissionCode).Append("\n");
            sb.Append("  ModuleName: ").Append(ModuleName).Append("\n");
            sb.Append("  ResourceName: ").Append(ResourceName).Append("\n");
            sb.Append("  ActionName: ").Append(ActionName).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  SortOrder: ").Append(SortOrder).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Permission)obj);
        }

        /// <summary>
        /// Returns true if Permission instances are equal
        /// </summary>
        /// <param name="other">Instance of Permission to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Permission other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    PermissionId == other.PermissionId ||
                    
                    PermissionId.Equals(other.PermissionId)
                ) && 
                (
                    PermissionCode == other.PermissionCode ||
                    
                    PermissionCode.Equals(other.PermissionCode)
                ) && 
                (
                    ModuleName == other.ModuleName ||
                    ModuleName != null &&
                    ModuleName.Equals(other.ModuleName)
                ) && 
                (
                    ResourceName == other.ResourceName ||
                    ResourceName != null &&
                    ResourceName.Equals(other.ResourceName)
                ) && 
                (
                    ActionName == other.ActionName ||
                    ActionName != null &&
                    ActionName.Equals(other.ActionName)
                ) && 
                (
                    Description == other.Description ||
                    Description != null &&
                    Description.Equals(other.Description)
                ) && 
                (
                    SortOrder == other.SortOrder ||
                    
                    SortOrder.Equals(other.SortOrder)
                ) && 
                (
                    Status == other.Status ||
                    
                    Status.Equals(other.Status)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + PermissionId.GetHashCode();
                    
                    hashCode = hashCode * 59 + PermissionCode.GetHashCode();
                    if (ModuleName != null)
                    hashCode = hashCode * 59 + ModuleName.GetHashCode();
                    if (ResourceName != null)
                    hashCode = hashCode * 59 + ResourceName.GetHashCode();
                    if (ActionName != null)
                    hashCode = hashCode * 59 + ActionName.GetHashCode();
                    if (Description != null)
                    hashCode = hashCode * 59 + Description.GetHashCode();
                    
                    hashCode = hashCode * 59 + SortOrder.GetHashCode();
                    
                    hashCode = hashCode * 59 + Status.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Permission left, Permission right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Permission left, Permission right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
