/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 操作人从当前登录用户推导，客户端不得传 operator_id。
    /// </summary>
    [DataContract]
    public partial class ProductionLineStatusUpdateRequest : IEquatable<ProductionLineStatusUpdateRequest>
    {
        /// <summary>
        /// Gets or Sets LineId
        /// </summary>
        [Required]
        [DataMember(Name="line_id", EmitDefaultValue=true)]
        public long LineId { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [Required]
        [DataMember(Name="status", EmitDefaultValue=true)]
        public ProductionLineRunStatus Status { get; set; }

        /// <summary>
        /// Gets or Sets CurrentOrderId
        /// </summary>
        [DataMember(Name="current_order_id", EmitDefaultValue=true)]
        public long? CurrentOrderId { get; set; }

        /// <summary>
        /// Gets or Sets CurrentMaterialId
        /// </summary>
        [DataMember(Name="current_material_id", EmitDefaultValue=true)]
        public long? CurrentMaterialId { get; set; }

        /// <summary>
        /// Gets or Sets FinishedQty
        /// </summary>
        [DataMember(Name="finished_qty", EmitDefaultValue=true)]
        public decimal? FinishedQty { get; set; }

        /// <summary>
        /// Gets or Sets Efficiency
        /// </summary>
        [Range(0, 1)]
        [DataMember(Name="efficiency", EmitDefaultValue=true)]
        public decimal? Efficiency { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProductionLineStatusUpdateRequest {\n");
            sb.Append("  LineId: ").Append(LineId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CurrentOrderId: ").Append(CurrentOrderId).Append("\n");
            sb.Append("  CurrentMaterialId: ").Append(CurrentMaterialId).Append("\n");
            sb.Append("  FinishedQty: ").Append(FinishedQty).Append("\n");
            sb.Append("  Efficiency: ").Append(Efficiency).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ProductionLineStatusUpdateRequest)obj);
        }

        /// <summary>
        /// Returns true if ProductionLineStatusUpdateRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of ProductionLineStatusUpdateRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProductionLineStatusUpdateRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    LineId == other.LineId ||
                    
                    LineId.Equals(other.LineId)
                ) && 
                (
                    Status == other.Status ||
                    
                    Status.Equals(other.Status)
                ) && 
                (
                    CurrentOrderId == other.CurrentOrderId ||
                    CurrentOrderId != null &&
                    CurrentOrderId.Equals(other.CurrentOrderId)
                ) && 
                (
                    CurrentMaterialId == other.CurrentMaterialId ||
                    CurrentMaterialId != null &&
                    CurrentMaterialId.Equals(other.CurrentMaterialId)
                ) && 
                (
                    FinishedQty == other.FinishedQty ||
                    FinishedQty != null &&
                    FinishedQty.Equals(other.FinishedQty)
                ) && 
                (
                    Efficiency == other.Efficiency ||
                    Efficiency != null &&
                    Efficiency.Equals(other.Efficiency)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + LineId.GetHashCode();
                    
                    hashCode = hashCode * 59 + Status.GetHashCode();
                    if (CurrentOrderId != null)
                    hashCode = hashCode * 59 + CurrentOrderId.GetHashCode();
                    if (CurrentMaterialId != null)
                    hashCode = hashCode * 59 + CurrentMaterialId.GetHashCode();
                    if (FinishedQty != null)
                    hashCode = hashCode * 59 + FinishedQty.GetHashCode();
                    if (Efficiency != null)
                    hashCode = hashCode * 59 + Efficiency.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ProductionLineStatusUpdateRequest left, ProductionLineStatusUpdateRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ProductionLineStatusUpdateRequest left, ProductionLineStatusUpdateRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
