/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ProductBatchTraceResult : IEquatable<ProductBatchTraceResult>
    {
        /// <summary>
        /// Gets or Sets OrderId
        /// </summary>
        [Required]
        [DataMember(Name="order_id", EmitDefaultValue=true)]
        public long OrderId { get; set; }

        /// <summary>
        /// 成品批次号，来自完工入库单。
        /// </summary>
        /// <value>成品批次号，来自完工入库单。</value>
        [DataMember(Name="batch_no", EmitDefaultValue=true)]
        public string BatchNo { get; set; }

        /// <summary>
        /// 成品物料编号。
        /// </summary>
        /// <value>成品物料编号。</value>
        [Required]
        [DataMember(Name="material_id", EmitDefaultValue=true)]
        public long MaterialId { get; set; }

        /// <summary>
        /// 跨表展示字段，来源于物料表 material.material_name，通过 production_order.material_id &#x3D; material.material_id 关联查询得到，权威物料实体由物料与 BOM 模块维护。
        /// </summary>
        /// <value>跨表展示字段，来源于物料表 material.material_name，通过 production_order.material_id &#x3D; material.material_id 关联查询得到，权威物料实体由物料与 BOM 模块维护。</value>
        [DataMember(Name="material_name", EmitDefaultValue=true)]
        public string MaterialName { get; set; }

        /// <summary>
        /// 跨模块拼装列表，来源于批次消耗关系表 batch_consumption，并通过 batch_consumption.item_id 关联采购订单明细表 purchase_order_item 得到该成品批次消耗的原材料批次。
        /// </summary>
        /// <value>跨模块拼装列表，来源于批次消耗关系表 batch_consumption，并通过 batch_consumption.item_id 关联采购订单明细表 purchase_order_item 得到该成品批次消耗的原材料批次。</value>
        [DataMember(Name="consumed_batches", EmitDefaultValue=false)]
        public List<ConsumedMaterialBatch> ConsumedBatches { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProductBatchTraceResult {\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  BatchNo: ").Append(BatchNo).Append("\n");
            sb.Append("  MaterialId: ").Append(MaterialId).Append("\n");
            sb.Append("  MaterialName: ").Append(MaterialName).Append("\n");
            sb.Append("  ConsumedBatches: ").Append(ConsumedBatches).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ProductBatchTraceResult)obj);
        }

        /// <summary>
        /// Returns true if ProductBatchTraceResult instances are equal
        /// </summary>
        /// <param name="other">Instance of ProductBatchTraceResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProductBatchTraceResult other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    OrderId == other.OrderId ||
                    
                    OrderId.Equals(other.OrderId)
                ) && 
                (
                    BatchNo == other.BatchNo ||
                    BatchNo != null &&
                    BatchNo.Equals(other.BatchNo)
                ) && 
                (
                    MaterialId == other.MaterialId ||
                    
                    MaterialId.Equals(other.MaterialId)
                ) && 
                (
                    MaterialName == other.MaterialName ||
                    MaterialName != null &&
                    MaterialName.Equals(other.MaterialName)
                ) && 
                (
                    ConsumedBatches == other.ConsumedBatches ||
                    ConsumedBatches != null &&
                    other.ConsumedBatches != null &&
                    ConsumedBatches.SequenceEqual(other.ConsumedBatches)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + OrderId.GetHashCode();
                    if (BatchNo != null)
                    hashCode = hashCode * 59 + BatchNo.GetHashCode();
                    
                    hashCode = hashCode * 59 + MaterialId.GetHashCode();
                    if (MaterialName != null)
                    hashCode = hashCode * 59 + MaterialName.GetHashCode();
                    if (ConsumedBatches != null)
                    hashCode = hashCode * 59 + ConsumedBatches.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ProductBatchTraceResult left, ProductBatchTraceResult right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ProductBatchTraceResult left, ProductBatchTraceResult right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
