/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ProductionOrderMaterialLockItem : IEquatable<ProductionOrderMaterialLockItem>
    {
        /// <summary>
        /// Gets or Sets MaterialId
        /// </summary>
        [Required]
        [DataMember(Name="material_id", EmitDefaultValue=true)]
        public long MaterialId { get; set; }

        /// <summary>
        /// Gets or Sets MaterialName
        /// </summary>
        [Required]
        [DataMember(Name="material_name", EmitDefaultValue=false)]
        public string MaterialName { get; set; }

        /// <summary>
        /// Gets or Sets Unit
        /// </summary>
        [Required]
        [DataMember(Name="unit", EmitDefaultValue=false)]
        public string Unit { get; set; }

        /// <summary>
        /// BOM 中生产一件父项所需的直接子项净用量。
        /// </summary>
        /// <value>BOM 中生产一件父项所需的直接子项净用量。</value>
        [Required]
        [DataMember(Name="bom_quantity", EmitDefaultValue=true)]
        public decimal BomQuantity { get; set; }

        /// <summary>
        /// Gets or Sets LossRate
        /// </summary>
        [Required]
        [Range(0, 1)]
        [DataMember(Name="loss_rate", EmitDefaultValue=true)]
        public decimal LossRate { get; set; }

        /// <summary>
        /// 订单完整需求量。按 plan_qty * bom_quantity / (1 - loss_rate) 计算，并向上保留两位小数； 同一物料存在多条直接 BOM 明细时按 material_id 汇总。 
        /// </summary>
        /// <value>订单完整需求量。按 plan_qty * bom_quantity / (1 - loss_rate) 计算，并向上保留两位小数； 同一物料存在多条直接 BOM 明细时按 material_id 汇总。 </value>
        [Required]
        [DataMember(Name="required_qty", EmitDefaultValue=true)]
        public decimal RequiredQty { get; set; }

        /// <summary>
        /// 该订单已经持有的 locked 状态库存数量。
        /// </summary>
        /// <value>该订单已经持有的 locked 状态库存数量。</value>
        [Required]
        [DataMember(Name="locked_qty", EmitDefaultValue=true)]
        public decimal LockedQty { get; set; }

        /// <summary>
        /// 本次审核通过时需要补充锁定的数量，等于 max(required_qty - locked_qty, 0)。
        /// </summary>
        /// <value>本次审核通过时需要补充锁定的数量，等于 max(required_qty - locked_qty, 0)。</value>
        [Required]
        [DataMember(Name="pending_lock_qty", EmitDefaultValue=true)]
        public decimal PendingLockQty { get; set; }

        /// <summary>
        /// 当前未被其他订单锁定的可用库存数量。
        /// </summary>
        /// <value>当前未被其他订单锁定的可用库存数量。</value>
        [Required]
        [DataMember(Name="available_qty", EmitDefaultValue=true)]
        public decimal AvailableQty { get; set; }

        /// <summary>
        /// 当前锁定缺口，等于 max(pending_lock_qty - available_qty, 0)。
        /// </summary>
        /// <value>当前锁定缺口，等于 max(pending_lock_qty - available_qty, 0)。</value>
        [Required]
        [DataMember(Name="shortage_qty", EmitDefaultValue=true)]
        public decimal ShortageQty { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProductionOrderMaterialLockItem {\n");
            sb.Append("  MaterialId: ").Append(MaterialId).Append("\n");
            sb.Append("  MaterialName: ").Append(MaterialName).Append("\n");
            sb.Append("  Unit: ").Append(Unit).Append("\n");
            sb.Append("  BomQuantity: ").Append(BomQuantity).Append("\n");
            sb.Append("  LossRate: ").Append(LossRate).Append("\n");
            sb.Append("  RequiredQty: ").Append(RequiredQty).Append("\n");
            sb.Append("  LockedQty: ").Append(LockedQty).Append("\n");
            sb.Append("  PendingLockQty: ").Append(PendingLockQty).Append("\n");
            sb.Append("  AvailableQty: ").Append(AvailableQty).Append("\n");
            sb.Append("  ShortageQty: ").Append(ShortageQty).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ProductionOrderMaterialLockItem)obj);
        }

        /// <summary>
        /// Returns true if ProductionOrderMaterialLockItem instances are equal
        /// </summary>
        /// <param name="other">Instance of ProductionOrderMaterialLockItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProductionOrderMaterialLockItem other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    MaterialId == other.MaterialId ||
                    
                    MaterialId.Equals(other.MaterialId)
                ) && 
                (
                    MaterialName == other.MaterialName ||
                    MaterialName != null &&
                    MaterialName.Equals(other.MaterialName)
                ) && 
                (
                    Unit == other.Unit ||
                    Unit != null &&
                    Unit.Equals(other.Unit)
                ) && 
                (
                    BomQuantity == other.BomQuantity ||
                    
                    BomQuantity.Equals(other.BomQuantity)
                ) && 
                (
                    LossRate == other.LossRate ||
                    
                    LossRate.Equals(other.LossRate)
                ) && 
                (
                    RequiredQty == other.RequiredQty ||
                    
                    RequiredQty.Equals(other.RequiredQty)
                ) && 
                (
                    LockedQty == other.LockedQty ||
                    
                    LockedQty.Equals(other.LockedQty)
                ) && 
                (
                    PendingLockQty == other.PendingLockQty ||
                    
                    PendingLockQty.Equals(other.PendingLockQty)
                ) && 
                (
                    AvailableQty == other.AvailableQty ||
                    
                    AvailableQty.Equals(other.AvailableQty)
                ) && 
                (
                    ShortageQty == other.ShortageQty ||
                    
                    ShortageQty.Equals(other.ShortageQty)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + MaterialId.GetHashCode();
                    if (MaterialName != null)
                    hashCode = hashCode * 59 + MaterialName.GetHashCode();
                    if (Unit != null)
                    hashCode = hashCode * 59 + Unit.GetHashCode();
                    
                    hashCode = hashCode * 59 + BomQuantity.GetHashCode();
                    
                    hashCode = hashCode * 59 + LossRate.GetHashCode();
                    
                    hashCode = hashCode * 59 + RequiredQty.GetHashCode();
                    
                    hashCode = hashCode * 59 + LockedQty.GetHashCode();
                    
                    hashCode = hashCode * 59 + PendingLockQty.GetHashCode();
                    
                    hashCode = hashCode * 59 + AvailableQty.GetHashCode();
                    
                    hashCode = hashCode * 59 + ShortageQty.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ProductionOrderMaterialLockItem left, ProductionOrderMaterialLockItem right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ProductionOrderMaterialLockItem left, ProductionOrderMaterialLockItem right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
