/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 产品成本核算明细，由后端读取 BOM、损耗率和采购价格后计算得到。
    /// </summary>
    [DataContract]
    public partial class ProductCostItem : IEquatable<ProductCostItem>
    {
        /// <summary>
        /// 物料编号，来源于 BOM 展开结果。
        /// </summary>
        /// <value>物料编号，来源于 BOM 展开结果。</value>
        [DataMember(Name="material_id", EmitDefaultValue=true)]
        public int MaterialId { get; set; }

        /// <summary>
        /// 物料名称，来源于 material.material_name。
        /// </summary>
        /// <value>物料名称，来源于 material.material_name。</value>
        [DataMember(Name="material_name", EmitDefaultValue=false)]
        public string MaterialName { get; set; }

        /// <summary>
        /// 净需求量，由后端按 BOM 层级和生产数量计算得到。
        /// </summary>
        /// <value>净需求量，由后端按 BOM 层级和生产数量计算得到。</value>
        [DataMember(Name="net_quantity", EmitDefaultValue=true)]
        public double NetQuantity { get; set; }

        /// <summary>
        /// 毛需求量，由后端按净需求量和 loss_rate 计算，公式为 net_quantity / (1 - loss_rate)。
        /// </summary>
        /// <value>毛需求量，由后端按净需求量和 loss_rate 计算，公式为 net_quantity / (1 - loss_rate)。</value>
        [DataMember(Name="gross_quantity", EmitDefaultValue=true)]
        public double GrossQuantity { get; set; }

        /// <summary>
        /// 单价，来源于采购价格、历史成交价或标准成本，单位为元。
        /// </summary>
        /// <value>单价，来源于采购价格、历史成交价或标准成本，单位为元。</value>
        [DataMember(Name="unit_price", EmitDefaultValue=true)]
        public double UnitPrice { get; set; }

        /// <summary>
        /// 明细金额，由后端按 gross_quantity × unit_price 计算，单位为元。
        /// </summary>
        /// <value>明细金额，由后端按 gross_quantity × unit_price 计算，单位为元。</value>
        [DataMember(Name="amount", EmitDefaultValue=true)]
        public double Amount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProductCostItem {\n");
            sb.Append("  MaterialId: ").Append(MaterialId).Append("\n");
            sb.Append("  MaterialName: ").Append(MaterialName).Append("\n");
            sb.Append("  NetQuantity: ").Append(NetQuantity).Append("\n");
            sb.Append("  GrossQuantity: ").Append(GrossQuantity).Append("\n");
            sb.Append("  UnitPrice: ").Append(UnitPrice).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ProductCostItem)obj);
        }

        /// <summary>
        /// Returns true if ProductCostItem instances are equal
        /// </summary>
        /// <param name="other">Instance of ProductCostItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProductCostItem other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    MaterialId == other.MaterialId ||
                    
                    MaterialId.Equals(other.MaterialId)
                ) && 
                (
                    MaterialName == other.MaterialName ||
                    MaterialName != null &&
                    MaterialName.Equals(other.MaterialName)
                ) && 
                (
                    NetQuantity == other.NetQuantity ||
                    
                    NetQuantity.Equals(other.NetQuantity)
                ) && 
                (
                    GrossQuantity == other.GrossQuantity ||
                    
                    GrossQuantity.Equals(other.GrossQuantity)
                ) && 
                (
                    UnitPrice == other.UnitPrice ||
                    
                    UnitPrice.Equals(other.UnitPrice)
                ) && 
                (
                    Amount == other.Amount ||
                    
                    Amount.Equals(other.Amount)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + MaterialId.GetHashCode();
                    if (MaterialName != null)
                    hashCode = hashCode * 59 + MaterialName.GetHashCode();
                    
                    hashCode = hashCode * 59 + NetQuantity.GetHashCode();
                    
                    hashCode = hashCode * 59 + GrossQuantity.GetHashCode();
                    
                    hashCode = hashCode * 59 + UnitPrice.GetHashCode();
                    
                    hashCode = hashCode * 59 + Amount.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ProductCostItem left, ProductCostItem right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ProductCostItem left, ProductCostItem right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
