/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 仅用于审核前展示，不预留库存。若订单存在不属于当前直接 BOM 的有效锁定，或某物料有效锁定 超过 required_qty，后端返回 code 409，要求先修正异常锁定记录。 
    /// </summary>
    [DataContract]
    public partial class ProductionOrderMaterialLockPreview : IEquatable<ProductionOrderMaterialLockPreview>
    {
        /// <summary>
        /// Gets or Sets OrderId
        /// </summary>
        [Required]
        [DataMember(Name="order_id", EmitDefaultValue=true)]
        public long OrderId { get; set; }

        /// <summary>
        /// 所有直接子项 shortage_qty 均为 0 时为 true。
        /// </summary>
        /// <value>所有直接子项 shortage_qty 均为 0 时为 true。</value>
        [Required]
        [DataMember(Name="can_approve", EmitDefaultValue=true)]
        public bool CanApprove { get; set; }

        /// <summary>
        /// Gets or Sets Items
        /// </summary>
        [Required]
        [DataMember(Name="items", EmitDefaultValue=false)]
        public List<ProductionOrderMaterialLockItem> Items { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProductionOrderMaterialLockPreview {\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  CanApprove: ").Append(CanApprove).Append("\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ProductionOrderMaterialLockPreview)obj);
        }

        /// <summary>
        /// Returns true if ProductionOrderMaterialLockPreview instances are equal
        /// </summary>
        /// <param name="other">Instance of ProductionOrderMaterialLockPreview to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProductionOrderMaterialLockPreview other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    OrderId == other.OrderId ||
                    
                    OrderId.Equals(other.OrderId)
                ) && 
                (
                    CanApprove == other.CanApprove ||
                    
                    CanApprove.Equals(other.CanApprove)
                ) && 
                (
                    Items == other.Items ||
                    Items != null &&
                    other.Items != null &&
                    Items.SequenceEqual(other.Items)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + OrderId.GetHashCode();
                    
                    hashCode = hashCode * 59 + CanApprove.GetHashCode();
                    if (Items != null)
                    hashCode = hashCode * 59 + Items.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ProductionOrderMaterialLockPreview left, ProductionOrderMaterialLockPreview right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ProductionOrderMaterialLockPreview left, ProductionOrderMaterialLockPreview right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
