/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ProductionOrderBrief : IEquatable<ProductionOrderBrief>
    {
        /// <summary>
        /// Gets or Sets OrderId
        /// </summary>
        /* <example>3001</example> */
        [Required]
        [DataMember(Name="order_id", EmitDefaultValue=true)]
        public long OrderId { get; set; }

        /// <summary>
        /// Gets or Sets MaterialId
        /// </summary>
        /* <example>1001</example> */
        [Required]
        [DataMember(Name="material_id", EmitDefaultValue=true)]
        public long MaterialId { get; set; }

        /// <summary>
        /// Gets or Sets MaterialName
        /// </summary>
        /* <example>工业叉车</example> */
        [DataMember(Name="material_name", EmitDefaultValue=false)]
        public string MaterialName { get; set; }

        /// <summary>
        /// Gets or Sets PlanQty
        /// </summary>
        /* <example>50</example> */
        [Required]
        [DataMember(Name="plan_qty", EmitDefaultValue=true)]
        public decimal PlanQty { get; set; }

        /// <summary>
        /// Gets or Sets FinishedQty
        /// </summary>
        /* <example>10</example> */
        [DataMember(Name="finished_qty", EmitDefaultValue=true)]
        public decimal FinishedQty { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [Required]
        [DataMember(Name="status", EmitDefaultValue=true)]
        public ProductionOrderStatus Status { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProductionOrderBrief {\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  MaterialId: ").Append(MaterialId).Append("\n");
            sb.Append("  MaterialName: ").Append(MaterialName).Append("\n");
            sb.Append("  PlanQty: ").Append(PlanQty).Append("\n");
            sb.Append("  FinishedQty: ").Append(FinishedQty).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ProductionOrderBrief)obj);
        }

        /// <summary>
        /// Returns true if ProductionOrderBrief instances are equal
        /// </summary>
        /// <param name="other">Instance of ProductionOrderBrief to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProductionOrderBrief other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    OrderId == other.OrderId ||
                    
                    OrderId.Equals(other.OrderId)
                ) && 
                (
                    MaterialId == other.MaterialId ||
                    
                    MaterialId.Equals(other.MaterialId)
                ) && 
                (
                    MaterialName == other.MaterialName ||
                    MaterialName != null &&
                    MaterialName.Equals(other.MaterialName)
                ) && 
                (
                    PlanQty == other.PlanQty ||
                    
                    PlanQty.Equals(other.PlanQty)
                ) && 
                (
                    FinishedQty == other.FinishedQty ||
                    
                    FinishedQty.Equals(other.FinishedQty)
                ) && 
                (
                    Status == other.Status ||
                    
                    Status.Equals(other.Status)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + OrderId.GetHashCode();
                    
                    hashCode = hashCode * 59 + MaterialId.GetHashCode();
                    if (MaterialName != null)
                    hashCode = hashCode * 59 + MaterialName.GetHashCode();
                    
                    hashCode = hashCode * 59 + PlanQty.GetHashCode();
                    
                    hashCode = hashCode * 59 + FinishedQty.GetHashCode();
                    
                    hashCode = hashCode * 59 + Status.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ProductionOrderBrief left, ProductionOrderBrief right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ProductionOrderBrief left, ProductionOrderBrief right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
