/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ProductionCompletionReportResult : IEquatable<ProductionCompletionReportResult>
    {
        /// <summary>
        /// Gets or Sets ProductionOrder
        /// </summary>
        [Required]
        [DataMember(Name="production_order", EmitDefaultValue=false)]
        public ProductionOrderDetail ProductionOrder { get; set; }

        /// <summary>
        /// Gets or Sets CompletionInbound
        /// </summary>
        [Required]
        [DataMember(Name="completion_inbound", EmitDefaultValue=false)]
        public CompletionInboundOrder CompletionInbound { get; set; }

        /// <summary>
        /// 本次报工后累计合格数量是否已达到计划数量，且订单是否已自动完工。
        /// </summary>
        /// <value>本次报工后累计合格数量是否已达到计划数量，且订单是否已自动完工。</value>
        [Required]
        [DataMember(Name="order_completed", EmitDefaultValue=true)]
        public bool OrderCompleted { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProductionCompletionReportResult {\n");
            sb.Append("  ProductionOrder: ").Append(ProductionOrder).Append("\n");
            sb.Append("  CompletionInbound: ").Append(CompletionInbound).Append("\n");
            sb.Append("  OrderCompleted: ").Append(OrderCompleted).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ProductionCompletionReportResult)obj);
        }

        /// <summary>
        /// Returns true if ProductionCompletionReportResult instances are equal
        /// </summary>
        /// <param name="other">Instance of ProductionCompletionReportResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProductionCompletionReportResult other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ProductionOrder == other.ProductionOrder ||
                    ProductionOrder != null &&
                    ProductionOrder.Equals(other.ProductionOrder)
                ) && 
                (
                    CompletionInbound == other.CompletionInbound ||
                    CompletionInbound != null &&
                    CompletionInbound.Equals(other.CompletionInbound)
                ) && 
                (
                    OrderCompleted == other.OrderCompleted ||
                    
                    OrderCompleted.Equals(other.OrderCompleted)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ProductionOrder != null)
                    hashCode = hashCode * 59 + ProductionOrder.GetHashCode();
                    if (CompletionInbound != null)
                    hashCode = hashCode * 59 + CompletionInbound.GetHashCode();
                    
                    hashCode = hashCode * 59 + OrderCompleted.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ProductionCompletionReportResult left, ProductionCompletionReportResult right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ProductionCompletionReportResult left, ProductionCompletionReportResult right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
