/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 产品成本核算结果，由后端汇总各物料成本明细得到。
    /// </summary>
    [DataContract]
    public partial class ProductCostResult : IEquatable<ProductCostResult>
    {
        /// <summary>
        /// 核算产品物料编号。
        /// </summary>
        /// <value>核算产品物料编号。</value>
        [DataMember(Name="material_id", EmitDefaultValue=true)]
        public int MaterialId { get; set; }

        /// <summary>
        /// 使用的 BOM 版本编号。
        /// </summary>
        /// <value>使用的 BOM 版本编号。</value>
        [DataMember(Name="version_id", EmitDefaultValue=true)]
        public int VersionId { get; set; }

        /// <summary>
        /// 产品总成本，由后端汇总所有明细 amount 得到，单位为元。
        /// </summary>
        /// <value>产品总成本，由后端汇总所有明细 amount 得到，单位为元。</value>
        [DataMember(Name="total_cost", EmitDefaultValue=true)]
        public double TotalCost { get; set; }

        /// <summary>
        /// 成本核算明细列表。
        /// </summary>
        /// <value>成本核算明细列表。</value>
        [DataMember(Name="items", EmitDefaultValue=false)]
        public List<ProductCostItem> Items { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProductCostResult {\n");
            sb.Append("  MaterialId: ").Append(MaterialId).Append("\n");
            sb.Append("  VersionId: ").Append(VersionId).Append("\n");
            sb.Append("  TotalCost: ").Append(TotalCost).Append("\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ProductCostResult)obj);
        }

        /// <summary>
        /// Returns true if ProductCostResult instances are equal
        /// </summary>
        /// <param name="other">Instance of ProductCostResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProductCostResult other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    MaterialId == other.MaterialId ||
                    
                    MaterialId.Equals(other.MaterialId)
                ) && 
                (
                    VersionId == other.VersionId ||
                    
                    VersionId.Equals(other.VersionId)
                ) && 
                (
                    TotalCost == other.TotalCost ||
                    
                    TotalCost.Equals(other.TotalCost)
                ) && 
                (
                    Items == other.Items ||
                    Items != null &&
                    other.Items != null &&
                    Items.SequenceEqual(other.Items)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + MaterialId.GetHashCode();
                    
                    hashCode = hashCode * 59 + VersionId.GetHashCode();
                    
                    hashCode = hashCode * 59 + TotalCost.GetHashCode();
                    if (Items != null)
                    hashCode = hashCode * 59 + Items.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ProductCostResult left, ProductCostResult right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ProductCostResult left, ProductCostResult right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
