/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ProductionCapacityEstimateResult : IEquatable<ProductionCapacityEstimateResult>
    {
        /// <summary>
        /// Gets or Sets CanDeliverOnTime
        /// </summary>
        [Required]
        [DataMember(Name="can_deliver_on_time", EmitDefaultValue=true)]
        public bool CanDeliverOnTime { get; set; }

        /// <summary>
        /// 物料是否齐套。
        /// </summary>
        /// <value>物料是否齐套。</value>
        [Required]
        [DataMember(Name="material_ready", EmitDefaultValue=true)]
        public bool MaterialReady { get; set; }

        /// <summary>
        /// 产能是否满足计划。
        /// </summary>
        /// <value>产能是否满足计划。</value>
        [Required]
        [DataMember(Name="capacity_ready", EmitDefaultValue=true)]
        public bool CapacityReady { get; set; }

        /// <summary>
        /// Gets or Sets LatestMaterialReadyDate
        /// </summary>
        [DataMember(Name="latest_material_ready_date", EmitDefaultValue=true)]
        public DateOnly? LatestMaterialReadyDate { get; set; }

        /// <summary>
        /// Gets or Sets EstimatedFinishDate
        /// </summary>
        [Required]
        [DataMember(Name="estimated_finish_date", EmitDefaultValue=true)]
        public DateOnly EstimatedFinishDate { get; set; }

        /// <summary>
        /// Gets or Sets RequiredWorkMinutes
        /// </summary>
        [DataMember(Name="required_work_minutes", EmitDefaultValue=true)]
        public decimal RequiredWorkMinutes { get; set; }

        /// <summary>
        /// Gets or Sets AvailableWorkMinutes
        /// </summary>
        [DataMember(Name="available_work_minutes", EmitDefaultValue=true)]
        public decimal AvailableWorkMinutes { get; set; }

        /// <summary>
        /// Gets or Sets RiskReason
        /// </summary>
        [DataMember(Name="risk_reason", EmitDefaultValue=true)]
        public string RiskReason { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProductionCapacityEstimateResult {\n");
            sb.Append("  CanDeliverOnTime: ").Append(CanDeliverOnTime).Append("\n");
            sb.Append("  MaterialReady: ").Append(MaterialReady).Append("\n");
            sb.Append("  CapacityReady: ").Append(CapacityReady).Append("\n");
            sb.Append("  LatestMaterialReadyDate: ").Append(LatestMaterialReadyDate).Append("\n");
            sb.Append("  EstimatedFinishDate: ").Append(EstimatedFinishDate).Append("\n");
            sb.Append("  RequiredWorkMinutes: ").Append(RequiredWorkMinutes).Append("\n");
            sb.Append("  AvailableWorkMinutes: ").Append(AvailableWorkMinutes).Append("\n");
            sb.Append("  RiskReason: ").Append(RiskReason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ProductionCapacityEstimateResult)obj);
        }

        /// <summary>
        /// Returns true if ProductionCapacityEstimateResult instances are equal
        /// </summary>
        /// <param name="other">Instance of ProductionCapacityEstimateResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProductionCapacityEstimateResult other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    CanDeliverOnTime == other.CanDeliverOnTime ||
                    
                    CanDeliverOnTime.Equals(other.CanDeliverOnTime)
                ) && 
                (
                    MaterialReady == other.MaterialReady ||
                    
                    MaterialReady.Equals(other.MaterialReady)
                ) && 
                (
                    CapacityReady == other.CapacityReady ||
                    
                    CapacityReady.Equals(other.CapacityReady)
                ) && 
                (
                    LatestMaterialReadyDate == other.LatestMaterialReadyDate ||
                    LatestMaterialReadyDate != null &&
                    LatestMaterialReadyDate.Equals(other.LatestMaterialReadyDate)
                ) && 
                (
                    EstimatedFinishDate == other.EstimatedFinishDate ||
                    
                    EstimatedFinishDate.Equals(other.EstimatedFinishDate)
                ) && 
                (
                    RequiredWorkMinutes == other.RequiredWorkMinutes ||
                    
                    RequiredWorkMinutes.Equals(other.RequiredWorkMinutes)
                ) && 
                (
                    AvailableWorkMinutes == other.AvailableWorkMinutes ||
                    
                    AvailableWorkMinutes.Equals(other.AvailableWorkMinutes)
                ) && 
                (
                    RiskReason == other.RiskReason ||
                    RiskReason != null &&
                    RiskReason.Equals(other.RiskReason)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + CanDeliverOnTime.GetHashCode();
                    
                    hashCode = hashCode * 59 + MaterialReady.GetHashCode();
                    
                    hashCode = hashCode * 59 + CapacityReady.GetHashCode();
                    if (LatestMaterialReadyDate != null)
                    hashCode = hashCode * 59 + LatestMaterialReadyDate.GetHashCode();
                    
                    hashCode = hashCode * 59 + EstimatedFinishDate.GetHashCode();
                    
                    hashCode = hashCode * 59 + RequiredWorkMinutes.GetHashCode();
                    
                    hashCode = hashCode * 59 + AvailableWorkMinutes.GetHashCode();
                    if (RiskReason != null)
                    hashCode = hashCode * 59 + RiskReason.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ProductionCapacityEstimateResult left, ProductionCapacityEstimateResult right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ProductionCapacityEstimateResult left, ProductionCapacityEstimateResult right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
