/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ProductionOrderUpdateRequest : IEquatable<ProductionOrderUpdateRequest>
    {
        /// <summary>
        /// Gets or Sets MaterialId
        /// </summary>
        [Required]
        [DataMember(Name="material_id", EmitDefaultValue=true)]
        public long MaterialId { get; set; }

        /// <summary>
        /// Gets or Sets VersionId
        /// </summary>
        [Required]
        [DataMember(Name="version_id", EmitDefaultValue=true)]
        public long VersionId { get; set; }

        /// <summary>
        /// Gets or Sets PlanQty
        /// </summary>
        [Required]
        [DataMember(Name="plan_qty", EmitDefaultValue=true)]
        public decimal PlanQty { get; set; }

        /// <summary>
        /// Gets or Sets PlanStart
        /// </summary>
        [Required]
        [DataMember(Name="plan_start", EmitDefaultValue=true)]
        public DateOnly PlanStart { get; set; }

        /// <summary>
        /// Gets or Sets PlanEnd
        /// </summary>
        [Required]
        [DataMember(Name="plan_end", EmitDefaultValue=true)]
        public DateOnly PlanEnd { get; set; }

        /// <summary>
        /// Gets or Sets OrderId
        /// </summary>
        [Required]
        [DataMember(Name="order_id", EmitDefaultValue=true)]
        public long OrderId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProductionOrderUpdateRequest {\n");
            sb.Append("  MaterialId: ").Append(MaterialId).Append("\n");
            sb.Append("  VersionId: ").Append(VersionId).Append("\n");
            sb.Append("  PlanQty: ").Append(PlanQty).Append("\n");
            sb.Append("  PlanStart: ").Append(PlanStart).Append("\n");
            sb.Append("  PlanEnd: ").Append(PlanEnd).Append("\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ProductionOrderUpdateRequest)obj);
        }

        /// <summary>
        /// Returns true if ProductionOrderUpdateRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of ProductionOrderUpdateRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProductionOrderUpdateRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    MaterialId == other.MaterialId ||
                    
                    MaterialId.Equals(other.MaterialId)
                ) && 
                (
                    VersionId == other.VersionId ||
                    
                    VersionId.Equals(other.VersionId)
                ) && 
                (
                    PlanQty == other.PlanQty ||
                    
                    PlanQty.Equals(other.PlanQty)
                ) && 
                (
                    PlanStart == other.PlanStart ||
                    
                    PlanStart.Equals(other.PlanStart)
                ) && 
                (
                    PlanEnd == other.PlanEnd ||
                    
                    PlanEnd.Equals(other.PlanEnd)
                ) && 
                (
                    OrderId == other.OrderId ||
                    
                    OrderId.Equals(other.OrderId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + MaterialId.GetHashCode();
                    
                    hashCode = hashCode * 59 + VersionId.GetHashCode();
                    
                    hashCode = hashCode * 59 + PlanQty.GetHashCode();
                    
                    hashCode = hashCode * 59 + PlanStart.GetHashCode();
                    
                    hashCode = hashCode * 59 + PlanEnd.GetHashCode();
                    
                    hashCode = hashCode * 59 + OrderId.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ProductionOrderUpdateRequest left, ProductionOrderUpdateRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ProductionOrderUpdateRequest left, ProductionOrderUpdateRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
