/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PurchaseDraftFromShortageResponseAllOfData : IEquatable<PurchaseDraftFromShortageResponseAllOfData>
    {
        /// <summary>
        /// Gets or Sets CreatedCount
        /// </summary>
        [DataMember(Name="created_count", EmitDefaultValue=true)]
        public int CreatedCount { get; set; }

        /// <summary>
        /// Gets or Sets Records
        /// </summary>
        [DataMember(Name="records", EmitDefaultValue=false)]
        public List<PurchaseOrder> Records { get; set; }

        /// <summary>
        /// 未找到默认供应商而无法生成草稿的物料。
        /// </summary>
        /// <value>未找到默认供应商而无法生成草稿的物料。</value>
        [DataMember(Name="unassigned_items", EmitDefaultValue=false)]
        public List<PurchaseDraftFromShortageResponseAllOfDataUnassignedItems> UnassignedItems { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PurchaseDraftFromShortageResponseAllOfData {\n");
            sb.Append("  CreatedCount: ").Append(CreatedCount).Append("\n");
            sb.Append("  Records: ").Append(Records).Append("\n");
            sb.Append("  UnassignedItems: ").Append(UnassignedItems).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PurchaseDraftFromShortageResponseAllOfData)obj);
        }

        /// <summary>
        /// Returns true if PurchaseDraftFromShortageResponseAllOfData instances are equal
        /// </summary>
        /// <param name="other">Instance of PurchaseDraftFromShortageResponseAllOfData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PurchaseDraftFromShortageResponseAllOfData other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    CreatedCount == other.CreatedCount ||
                    
                    CreatedCount.Equals(other.CreatedCount)
                ) && 
                (
                    Records == other.Records ||
                    Records != null &&
                    other.Records != null &&
                    Records.SequenceEqual(other.Records)
                ) && 
                (
                    UnassignedItems == other.UnassignedItems ||
                    UnassignedItems != null &&
                    other.UnassignedItems != null &&
                    UnassignedItems.SequenceEqual(other.UnassignedItems)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + CreatedCount.GetHashCode();
                    if (Records != null)
                    hashCode = hashCode * 59 + Records.GetHashCode();
                    if (UnassignedItems != null)
                    hashCode = hashCode * 59 + UnassignedItems.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(PurchaseDraftFromShortageResponseAllOfData left, PurchaseDraftFromShortageResponseAllOfData right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PurchaseDraftFromShortageResponseAllOfData left, PurchaseDraftFromShortageResponseAllOfData right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
