/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PurchaseOverdueReminderHandleRequest : IEquatable<PurchaseOverdueReminderHandleRequest>
    {
        /// <summary>
        /// Gets or Sets ReminderId
        /// </summary>
        [Required]
        [DataMember(Name="reminder_id", EmitDefaultValue=true)]
        public long ReminderId { get; set; }


        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<StatusEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum StatusEnum
        {
            
            /// <summary>
            /// Enum UrgedEnum for urged
            /// </summary>
            [EnumMember(Value = "urged")]
            UrgedEnum = 1,
            
            /// <summary>
            /// Enum ReceivedEnum for received
            /// </summary>
            [EnumMember(Value = "received")]
            ReceivedEnum = 2
        }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [Required]
        [DataMember(Name="status", EmitDefaultValue=true)]
        public StatusEnum Status { get; set; }

        /// <summary>
        /// Gets or Sets Remark
        /// </summary>
        [DataMember(Name="remark", EmitDefaultValue=true)]
        public string Remark { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PurchaseOverdueReminderHandleRequest {\n");
            sb.Append("  ReminderId: ").Append(ReminderId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Remark: ").Append(Remark).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PurchaseOverdueReminderHandleRequest)obj);
        }

        /// <summary>
        /// Returns true if PurchaseOverdueReminderHandleRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of PurchaseOverdueReminderHandleRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PurchaseOverdueReminderHandleRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ReminderId == other.ReminderId ||
                    
                    ReminderId.Equals(other.ReminderId)
                ) && 
                (
                    Status == other.Status ||
                    
                    Status.Equals(other.Status)
                ) && 
                (
                    Remark == other.Remark ||
                    Remark != null &&
                    Remark.Equals(other.Remark)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + ReminderId.GetHashCode();
                    
                    hashCode = hashCode * 59 + Status.GetHashCode();
                    if (Remark != null)
                    hashCode = hashCode * 59 + Remark.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(PurchaseOverdueReminderHandleRequest left, PurchaseOverdueReminderHandleRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PurchaseOverdueReminderHandleRequest left, PurchaseOverdueReminderHandleRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
