/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
        /// <summary>
        /// 采购逾期提醒状态。pending_urge 待催交，可催交或标记到货；urged 已催交，可继续备注或标记到货；received 已到货，流程结束。允许流转：pending_urge -> urged/received，urged -> received。
        /// </summary>
        /// <value>采购逾期提醒状态。pending_urge 待催交，可催交或标记到货；urged 已催交，可继续备注或标记到货；received 已到货，流程结束。允许流转：pending_urge -> urged/received，urged -> received。</value>
        [TypeConverter(typeof(CustomEnumConverter<PurchaseOverdueReminderStatus>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum PurchaseOverdueReminderStatus
        {
            
            /// <summary>
            /// Enum PendingUrgeEnum for pending_urge
            /// </summary>
            [EnumMember(Value = "pending_urge")]
            PendingUrgeEnum = 1,
            
            /// <summary>
            /// Enum UrgedEnum for urged
            /// </summary>
            [EnumMember(Value = "urged")]
            UrgedEnum = 2,
            
            /// <summary>
            /// Enum ReceivedEnum for received
            /// </summary>
            [EnumMember(Value = "received")]
            ReceivedEnum = 3
        }
}
