/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
        /// <summary>
        /// 采购订单状态。draft 草稿，可编辑、提交、取消；submitted 已提交，可收货、取消；partial_received 部分到货，可继续收货；completed 已完成，不可修改；cancelled 已取消，不可继续操作。允许流转：draft -> submitted/cancelled，submitted -> partial_received/completed/cancelled，partial_received -> completed。
        /// </summary>
        /// <value>采购订单状态。draft 草稿，可编辑、提交、取消；submitted 已提交，可收货、取消；partial_received 部分到货，可继续收货；completed 已完成，不可修改；cancelled 已取消，不可继续操作。允许流转：draft -> submitted/cancelled，submitted -> partial_received/completed/cancelled，partial_received -> completed。</value>
        [TypeConverter(typeof(CustomEnumConverter<PurchaseOrderStatus>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum PurchaseOrderStatus
        {
            
            /// <summary>
            /// Enum DraftEnum for draft
            /// </summary>
            [EnumMember(Value = "draft")]
            DraftEnum = 1,
            
            /// <summary>
            /// Enum SubmittedEnum for submitted
            /// </summary>
            [EnumMember(Value = "submitted")]
            SubmittedEnum = 2,
            
            /// <summary>
            /// Enum PartialReceivedEnum for partial_received
            /// </summary>
            [EnumMember(Value = "partial_received")]
            PartialReceivedEnum = 3,
            
            /// <summary>
            /// Enum CompletedEnum for completed
            /// </summary>
            [EnumMember(Value = "completed")]
            CompletedEnum = 4,
            
            /// <summary>
            /// Enum CancelledEnum for cancelled
            /// </summary>
            [EnumMember(Value = "cancelled")]
            CancelledEnum = 5
        }
}
