/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 反向追溯结果项，由后端以指定子物料为起点向上递归查找父项和最终产品得到。
    /// </summary>
    [DataContract]
    public partial class ReverseTraceItem : IEquatable<ReverseTraceItem>
    {
        /// <summary>
        /// 受影响的产品物料编号，来源于递归追溯到的父级物料。
        /// </summary>
        /// <value>受影响的产品物料编号，来源于递归追溯到的父级物料。</value>
        [DataMember(Name="product_material_id", EmitDefaultValue=true)]
        public int ProductMaterialId { get; set; }

        /// <summary>
        /// 受影响的产品物料名称，来源于 material.material_name。
        /// </summary>
        /// <value>受影响的产品物料名称，来源于 material.material_name。</value>
        [DataMember(Name="product_material_name", EmitDefaultValue=false)]
        public string ProductMaterialName { get; set; }

        /// <summary>
        /// BOM 版本编号，来源于 bom_version.version_id。
        /// </summary>
        /// <value>BOM 版本编号，来源于 bom_version.version_id。</value>
        [DataMember(Name="version_id", EmitDefaultValue=true)]
        public int VersionId { get; set; }

        /// <summary>
        /// BOM 版本号，来源于 bom_version.version_no。
        /// </summary>
        /// <value>BOM 版本号，来源于 bom_version.version_no。</value>
        [DataMember(Name="version_no", EmitDefaultValue=false)]
        public string VersionNo { get; set; }


        /// <summary>
        /// 版本状态，由后端根据有效期判断；effective 表示当前有效，history 表示历史版本。
        /// </summary>
        /// <value>版本状态，由后端根据有效期判断；effective 表示当前有效，history 表示历史版本。</value>
        [TypeConverter(typeof(CustomEnumConverter<VersionStatusEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum VersionStatusEnum
        {
            
            /// <summary>
            /// Enum EffectiveEnum for effective
            /// </summary>
            [EnumMember(Value = "effective")]
            EffectiveEnum = 1,
            
            /// <summary>
            /// Enum HistoryEnum for history
            /// </summary>
            [EnumMember(Value = "history")]
            HistoryEnum = 2
        }

        /// <summary>
        /// 版本状态，由后端根据有效期判断；effective 表示当前有效，history 表示历史版本。
        /// </summary>
        /// <value>版本状态，由后端根据有效期判断；effective 表示当前有效，history 表示历史版本。</value>
        [DataMember(Name="version_status", EmitDefaultValue=true)]
        public VersionStatusEnum VersionStatus { get; set; }

        /// <summary>
        /// 从指定子物料向上追溯到产品的物料编号路径。
        /// </summary>
        /// <value>从指定子物料向上追溯到产品的物料编号路径。</value>
        [DataMember(Name="path", EmitDefaultValue=false)]
        public string Path { get; set; }

        /// <summary>
        /// 追溯层级，由后端递归计算。
        /// </summary>
        /// <value>追溯层级，由后端递归计算。</value>
        [DataMember(Name="depth", EmitDefaultValue=true)]
        public int Depth { get; set; }

        /// <summary>
        /// 当前父子关系的单位用量，来源于 bom.quantity。
        /// </summary>
        /// <value>当前父子关系的单位用量，来源于 bom.quantity。</value>
        [DataMember(Name="quantity", EmitDefaultValue=true)]
        public double Quantity { get; set; }

        /// <summary>
        /// 累计影响用量，由后端按追溯路径上的 quantity 乘积计算得到。
        /// </summary>
        /// <value>累计影响用量，由后端按追溯路径上的 quantity 乘积计算得到。</value>
        [DataMember(Name="accumulated_quantity", EmitDefaultValue=true)]
        public double AccumulatedQuantity { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReverseTraceItem {\n");
            sb.Append("  ProductMaterialId: ").Append(ProductMaterialId).Append("\n");
            sb.Append("  ProductMaterialName: ").Append(ProductMaterialName).Append("\n");
            sb.Append("  VersionId: ").Append(VersionId).Append("\n");
            sb.Append("  VersionNo: ").Append(VersionNo).Append("\n");
            sb.Append("  VersionStatus: ").Append(VersionStatus).Append("\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("  Depth: ").Append(Depth).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  AccumulatedQuantity: ").Append(AccumulatedQuantity).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ReverseTraceItem)obj);
        }

        /// <summary>
        /// Returns true if ReverseTraceItem instances are equal
        /// </summary>
        /// <param name="other">Instance of ReverseTraceItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReverseTraceItem other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ProductMaterialId == other.ProductMaterialId ||
                    
                    ProductMaterialId.Equals(other.ProductMaterialId)
                ) && 
                (
                    ProductMaterialName == other.ProductMaterialName ||
                    ProductMaterialName != null &&
                    ProductMaterialName.Equals(other.ProductMaterialName)
                ) && 
                (
                    VersionId == other.VersionId ||
                    
                    VersionId.Equals(other.VersionId)
                ) && 
                (
                    VersionNo == other.VersionNo ||
                    VersionNo != null &&
                    VersionNo.Equals(other.VersionNo)
                ) && 
                (
                    VersionStatus == other.VersionStatus ||
                    
                    VersionStatus.Equals(other.VersionStatus)
                ) && 
                (
                    Path == other.Path ||
                    Path != null &&
                    Path.Equals(other.Path)
                ) && 
                (
                    Depth == other.Depth ||
                    
                    Depth.Equals(other.Depth)
                ) && 
                (
                    Quantity == other.Quantity ||
                    
                    Quantity.Equals(other.Quantity)
                ) && 
                (
                    AccumulatedQuantity == other.AccumulatedQuantity ||
                    
                    AccumulatedQuantity.Equals(other.AccumulatedQuantity)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + ProductMaterialId.GetHashCode();
                    if (ProductMaterialName != null)
                    hashCode = hashCode * 59 + ProductMaterialName.GetHashCode();
                    
                    hashCode = hashCode * 59 + VersionId.GetHashCode();
                    if (VersionNo != null)
                    hashCode = hashCode * 59 + VersionNo.GetHashCode();
                    
                    hashCode = hashCode * 59 + VersionStatus.GetHashCode();
                    if (Path != null)
                    hashCode = hashCode * 59 + Path.GetHashCode();
                    
                    hashCode = hashCode * 59 + Depth.GetHashCode();
                    
                    hashCode = hashCode * 59 + Quantity.GetHashCode();
                    
                    hashCode = hashCode * 59 + AccumulatedQuantity.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ReverseTraceItem left, ReverseTraceItem right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ReverseTraceItem left, ReverseTraceItem right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
