/*
 * 数据库设计项目 API
 *
 * 项目 OpenAPI 总入口，按业务模块汇总接口定义。
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class StockLockRecordPageResponse : IEquatable<StockLockRecordPageResponse>
    {

        /// <summary>
        /// 业务状态码，只使用 200、400、401、403、404、409、500。
        /// </summary>
        /// <value>业务状态码，只使用 200、400、401、403、404、409、500。</value>
        
        public enum CodeEnum
        {
            
            /// <summary>
            /// Enum _200Enum for 200
            /// </summary>
            
            _200Enum = 200,
            
            /// <summary>
            /// Enum _400Enum for 400
            /// </summary>
            
            _400Enum = 400,
            
            /// <summary>
            /// Enum _401Enum for 401
            /// </summary>
            
            _401Enum = 401,
            
            /// <summary>
            /// Enum _403Enum for 403
            /// </summary>
            
            _403Enum = 403,
            
            /// <summary>
            /// Enum _404Enum for 404
            /// </summary>
            
            _404Enum = 404,
            
            /// <summary>
            /// Enum _409Enum for 409
            /// </summary>
            
            _409Enum = 409,
            
            /// <summary>
            /// Enum _500Enum for 500
            /// </summary>
            
            _500Enum = 500
        }

        /// <summary>
        /// 业务状态码，只使用 200、400、401、403、404、409、500。
        /// </summary>
        /// <value>业务状态码，只使用 200、400、401、403、404、409、500。</value>
        /* <example>200</example> */
        [Required]
        [DataMember(Name="code", EmitDefaultValue=true)]
        public CodeEnum Code { get; set; }

        /// <summary>
        /// 返回结果说明。
        /// </summary>
        /// <value>返回结果说明。</value>
        /* <example>操作成功</example> */
        [Required]
        [DataMember(Name="message", EmitDefaultValue=false)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [Required]
        [DataMember(Name="data", EmitDefaultValue=true)]
        public Object Data { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StockLockRecordPageResponse {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((StockLockRecordPageResponse)obj);
        }

        /// <summary>
        /// Returns true if StockLockRecordPageResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of StockLockRecordPageResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StockLockRecordPageResponse other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Code == other.Code ||
                    
                    Code.Equals(other.Code)
                ) && 
                (
                    Message == other.Message ||
                    Message != null &&
                    Message.Equals(other.Message)
                ) && 
                (
                    Data == other.Data ||
                    Data != null &&
                    Data.Equals(other.Data)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + Code.GetHashCode();
                    if (Message != null)
                    hashCode = hashCode * 59 + Message.GetHashCode();
                    if (Data != null)
                    hashCode = hashCode * 59 + Data.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(StockLockRecordPageResponse left, StockLockRecordPageResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(StockLockRecordPageResponse left, StockLockRecordPageResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
