name: Deploy API Doc to GitHub Pages

on:
    push:
        branches: [main]
        paths:
          - api/**
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build-and-deploy:
        concurrency:
            group: deploy-api-doc
            cancel-in-progress: false
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup Pages
              uses: actions/configure-pages@v5

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v4
              with:
                  path: ./api
                  retention-days: 7

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
